#ifndef _GPIO_H_
#define _GPIO_H_
#include<stm32f10x.h>

//enable the gpio clock
#define GPIOA_CLK_ENA() {RCC->APB2ENR|=1<<2;}
#define GPIOB_CLK_ENA() {RCC->APB2ENR|=1<<3;}
#define GPIOC_CLK_ENA() {RCC->APB2ENR|=1<<4;}
#define GPIOD_CLK_ENA() {RCC->APB2ENR|=1<<5;}
#define GPIOE_CLK_ENA() {RCC->APB2ENR|=1<<6;}
#define GPIOF_CLK_ENA() {RCC->APB2ENR|=1<<7;}
#define GPIOG_CLK_ENA() {RCC->APB2ENR|=1<<8;}

//JTAG and SWD Pin Config
//PA13/JTMS/SWDIO  PA14/JTCK/SWCLK  PA15/JTDI  PB3/JTDO/SWO  PB4/NJTRST
//000       X             X             X           X            X
//001       X             X             X           X          (free)
//010       X             X           (free)      (free)       (free)
//100     (free)        (free)        (free)      (free)       (free)

#define JTAG_ENABLE_SWD_ENABLE     0X00
#define JTAG_DISABLE_SWD_ENABLE    0X02
#define JTAG_DISABLE_SWD_DISABLE   0X04

#define BITBAND(addr, bitnum) ((addr & 0xF0000000)+0x2000000+((addr &0xFFFFF)<<5)+(bitnum<<2)) 
#define MEM_ADDR(addr)  *((volatile unsigned long  *)(addr)) 
#define BIT_ADDR(addr, bitnum)   MEM_ADDR(BITBAND(addr, bitnum)) 

#define GPIOA_ODR_Addr    (GPIOA_BASE+12) //0x4001080C 
#define GPIOB_ODR_Addr    (GPIOB_BASE+12) //0x40010C0C 
#define GPIOC_ODR_Addr    (GPIOC_BASE+12) //0x4001100C 
#define GPIOD_ODR_Addr    (GPIOD_BASE+12) //0x4001140C 
#define GPIOE_ODR_Addr    (GPIOE_BASE+12) //0x4001180C 
#define GPIOF_ODR_Addr    (GPIOF_BASE+12) //0x40011A0C    
#define GPIOG_ODR_Addr    (GPIOG_BASE+12) //0x40011E0C    

#define GPIOA_IDR_Addr    (GPIOA_BASE+8) //0x40010808 
#define GPIOB_IDR_Addr    (GPIOB_BASE+8) //0x40010C08 
#define GPIOC_IDR_Addr    (GPIOC_BASE+8) //0x40011008 
#define GPIOD_IDR_Addr    (GPIOD_BASE+8) //0x40011408 
#define GPIOE_IDR_Addr    (GPIOE_BASE+8) //0x40011808 
#define GPIOF_IDR_Addr    (GPIOF_BASE+8) //0x40011A08 
#define GPIOG_IDR_Addr    (GPIOG_BASE+8) //0x40011E08 
 
#define PAout(n)   BIT_ADDR(GPIOA_ODR_Addr,n)   
#define PAin(n)    BIT_ADDR(GPIOA_IDR_Addr,n)  
#define PBout(n)   BIT_ADDR(GPIOB_ODR_Addr,n)  
#define PBin(n)    BIT_ADDR(GPIOB_IDR_Addr,n)  
#define PCout(n)   BIT_ADDR(GPIOC_ODR_Addr,n)  
#define PCin(n)    BIT_ADDR(GPIOC_IDR_Addr,n)  
#define PDout(n)   BIT_ADDR(GPIOD_ODR_Addr,n)  
#define PDin(n)    BIT_ADDR(GPIOD_IDR_Addr,n)  
#define PEout(n)   BIT_ADDR(GPIOE_ODR_Addr,n)  
#define PEin(n)    BIT_ADDR(GPIOE_IDR_Addr,n) 
#define PFout(n)   BIT_ADDR(GPIOF_ODR_Addr,n)  
#define PFin(n)    BIT_ADDR(GPIOF_IDR_Addr,n) 
#define PGout(n)   BIT_ADDR(GPIOG_ODR_Addr,n)  
#define PGin(n)    BIT_ADDR(GPIOG_IDR_Addr,n)  

#define GPIOA_0_OUT_PP()  {GPIOA->CRL&=0XFFFFFFF0;GPIOA->CRL|=3<<0;}
#define GPIOA_1_OUT_PP()  {GPIOA->CRL&=0XFFFFFF0F;GPIOA->CRL|=3<<4;}
#define GPIOA_2_OUT_PP()  {GPIOA->CRL&=0XFFFFF0FF;GPIOA->CRL|=3<<8;}
#define GPIOA_3_OUT_PP()  {GPIOA->CRL&=0XFFFF0FFF;GPIOA->CRL|=3<<12;}
#define GPIOA_4_OUT_PP()  {GPIOA->CRL&=0XFFF0FFFF;GPIOA->CRL|=3<<16;}
#define GPIOA_5_OUT_PP()  {GPIOA->CRL&=0XFF0FFFFF;GPIOA->CRL|=3<<20;}
#define GPIOA_6_OUT_PP()  {GPIOA->CRL&=0XF0FFFFFF;GPIOA->CRL|=3<<24;}
#define GPIOA_7_OUT_PP()  {GPIOA->CRL&=0X0FFFFFFF;GPIOA->CRL|=3<<28;}
#define GPIOA_8_OUT_PP()  {GPIOA->CRH&=0XFFFFFFF0;GPIOA->CRH|=3<<0;}
#define GPIOA_9_OUT_PP()  {GPIOA->CRH&=0XFFFFFF0F;GPIOA->CRH|=3<<4;}
#define GPIOA_10_OUT_PP() {GPIOA->CRH&=0XFFFFF0FF;GPIOA->CRH|=3<<8;}
#define GPIOA_11_OUT_PP() {GPIOA->CRH&=0XFFFF0FFF;GPIOA->CRH|=3<<12;}
#define GPIOA_12_OUT_PP() {GPIOA->CRH&=0XFFF0FFFF;GPIOA->CRH|=3<<16;}
#define GPIOA_13_OUT_PP() {GPIOA->CRH&=0XFF0FFFFF;GPIOA->CRH|=3<<20;}
#define GPIOA_14_OUT_PP() {GPIOA->CRH&=0XF0FFFFFF;GPIOA->CRH|=3<<24;}
#define GPIOA_15_OUT_PP() {GPIOA->CRH&=0X0FFFFFFF;GPIOA->CRH|=3<<28;}

#define GPIOB_0_OUT_PP()  {GPIOB->CRL&=0XFFFFFFF0;GPIOB->CRL|=3<<0;}
#define GPIOB_1_OUT_PP()  {GPIOB->CRL&=0XFFFFFF0F;GPIOB->CRL|=3<<4;}
#define GPIOB_2_OUT_PP()  {GPIOB->CRL&=0XFFFFF0FF;GPIOB->CRL|=3<<8;}
#define GPIOB_3_OUT_PP()  {GPIOB->CRL&=0XFFFF0FFF;GPIOB->CRL|=3<<12;}
#define GPIOB_4_OUT_PP()  {GPIOB->CRL&=0XFFF0FFFF;GPIOB->CRL|=3<<16;}
#define GPIOB_5_OUT_PP()  {GPIOB->CRL&=0XFF0FFFFF;GPIOB->CRL|=3<<20;}
#define GPIOB_6_OUT_PP()  {GPIOB->CRL&=0XF0FFFFFF;GPIOB->CRL|=3<<24;}
#define GPIOB_7_OUT_PP()  {GPIOB->CRL&=0X0FFFFFFF;GPIOB->CRL|=3<<28;}
#define GPIOB_8_OUT_PP()  {GPIOB->CRH&=0XFFFFFFF0;GPIOB->CRH|=3<<0;}
#define GPIOB_9_OUT_PP()  {GPIOB->CRH&=0XFFFFFF0F;GPIOB->CRH|=3<<4;}
#define GPIOB_10_OUT_PP() {GPIOB->CRH&=0XFFFFF0FF;GPIOB->CRH|=3<<8;}
#define GPIOB_11_OUT_PP() {GPIOB->CRH&=0XFFFF0FFF;GPIOB->CRH|=3<<12;}
#define GPIOB_12_OUT_PP() {GPIOB->CRH&=0XFFF0FFFF;GPIOB->CRH|=3<<16;}
#define GPIOB_13_OUT_PP() {GPIOB->CRH&=0XFF0FFFFF;GPIOB->CRH|=3<<20;}
#define GPIOB_14_OUT_PP() {GPIOB->CRH&=0XF0FFFFFF;GPIOB->CRH|=3<<24;}
#define GPIOB_15_OUT_PP() {GPIOB->CRH&=0X0FFFFFFF;GPIOB->CRH|=3<<28;}

#define GPIOC_0_OUT_PP()  {GPIOC->CRL&=0XFFFFFFF0;GPIOC->CRL|=3<<0;}
#define GPIOC_1_OUT_PP()  {GPIOC->CRL&=0XFFFFFF0F;GPIOC->CRL|=3<<4;}
#define GPIOC_2_OUT_PP()  {GPIOC->CRL&=0XFFFFF0FF;GPIOC->CRL|=3<<8;}
#define GPIOC_3_OUT_PP()  {GPIOC->CRL&=0XFFFF0FFF;GPIOC->CRL|=3<<12;}
#define GPIOC_4_OUT_PP()  {GPIOC->CRL&=0XFFF0FFFF;GPIOC->CRL|=3<<16;}
#define GPIOC_5_OUT_PP()  {GPIOC->CRL&=0XFF0FFFFF;GPIOC->CRL|=3<<20;}
#define GPIOC_6_OUT_PP()  {GPIOC->CRL&=0XF0FFFFFF;GPIOC->CRL|=3<<24;}
#define GPIOC_7_OUT_PP()  {GPIOC->CRL&=0X0FFFFFFF;GPIOC->CRL|=3<<28;}
#define GPIOC_8_OUT_PP()  {GPIOC->CRH&=0XFFFFFFF0;GPIOC->CRH|=3<<0;}
#define GPIOC_9_OUT_PP()  {GPIOC->CRH&=0XFFFFFF0F;GPIOC->CRH|=3<<4;}
#define GPIOC_10_OUT_PP() {GPIOC->CRH&=0XFFFFF0FF;GPIOC->CRH|=3<<8;}
#define GPIOC_11_OUT_PP() {GPIOC->CRH&=0XFFFF0FFF;GPIOC->CRH|=3<<12;}
#define GPIOC_12_OUT_PP() {GPIOC->CRH&=0XFFF0FFFF;GPIOC->CRH|=3<<16;}
#define GPIOC_13_OUT_PP() {GPIOC->CRH&=0XFF0FFFFF;GPIOC->CRH|=3<<20;}
#define GPIOC_14_OUT_PP() {GPIOC->CRH&=0XF0FFFFFF;GPIOC->CRH|=3<<24;}
#define GPIOC_15_OUT_PP() {GPIOC->CRH&=0X0FFFFFFF;GPIOC->CRH|=3<<28;}

#define GPIOD_0_OUT_PP()  {GPIOD->CRL&=0XFFFFFFF0;GPIOD->CRL|=3<<0;}
#define GPIOD_1_OUT_PP()  {GPIOD->CRL&=0XFFFFFF0F;GPIOD->CRL|=3<<4;}
#define GPIOD_2_OUT_PP()  {GPIOD->CRL&=0XFFFFF0FF;GPIOD->CRL|=3<<8;}
#define GPIOD_3_OUT_PP()  {GPIOD->CRL&=0XFFFF0FFF;GPIOD->CRL|=3<<12;}
#define GPIOD_4_OUT_PP()  {GPIOD->CRL&=0XFFF0FFFF;GPIOD->CRL|=3<<16;}
#define GPIOD_5_OUT_PP()  {GPIOD->CRL&=0XFF0FFFFF;GPIOD->CRL|=3<<20;}
#define GPIOD_6_OUT_PP()  {GPIOD->CRL&=0XF0FFFFFF;GPIOD->CRL|=3<<24;}
#define GPIOD_7_OUT_PP()  {GPIOD->CRL&=0X0FFFFFFF;GPIOD->CRL|=3<<28;}
#define GPIOD_8_OUT_PP()  {GPIOD->CRH&=0XFFFFFFF0;GPIOD->CRH|=3<<0;}
#define GPIOD_9_OUT_PP()  {GPIOD->CRH&=0XFFFFFF0F;GPIOD->CRH|=3<<4;}
#define GPIOD_10_OUT_PP() {GPIOD->CRH&=0XFFFFF0FF;GPIOD->CRH|=3<<8;}
#define GPIOD_11_OUT_PP() {GPIOD->CRH&=0XFFFF0FFF;GPIOD->CRH|=3<<12;}
#define GPIOD_12_OUT_PP() {GPIOD->CRH&=0XFFF0FFFF;GPIOD->CRH|=3<<16;}
#define GPIOD_13_OUT_PP() {GPIOD->CRH&=0XFF0FFFFF;GPIOD->CRH|=3<<20;}
#define GPIOD_14_OUT_PP() {GPIOD->CRH&=0XF0FFFFFF;GPIOD->CRH|=3<<24;}
#define GPIOD_15_OUT_PP() {GPIOD->CRH&=0X0FFFFFFF;GPIOD->CRH|=3<<28;}

#define GPIOE_0_OUT_PP()  {GPIOE->CRL&=0XFFFFFFF0;GPIOE->CRL|=3<<0;}
#define GPIOE_1_OUT_PP()  {GPIOE->CRL&=0XFFFFFF0F;GPIOE->CRL|=3<<4;}
#define GPIOE_2_OUT_PP()  {GPIOE->CRL&=0XFFFFF0FF;GPIOE->CRL|=3<<8;}
#define GPIOE_3_OUT_PP()  {GPIOE->CRL&=0XFFFF0FFF;GPIOE->CRL|=3<<12;}
#define GPIOE_4_OUT_PP()  {GPIOE->CRL&=0XFFF0FFFF;GPIOE->CRL|=3<<16;}
#define GPIOE_5_OUT_PP()  {GPIOE->CRL&=0XFF0FFFFF;GPIOE->CRL|=3<<20;}
#define GPIOE_6_OUT_PP()  {GPIOE->CRL&=0XF0FFFFFF;GPIOE->CRL|=3<<24;}
#define GPIOE_7_OUT_PP()  {GPIOE->CRL&=0X0FFFFFFF;GPIOE->CRL|=3<<28;}
#define GPIOE_8_OUT_PP()  {GPIOE->CRH&=0XFFFFFFF0;GPIOE->CRH|=3<<0;}
#define GPIOE_9_OUT_PP()  {GPIOE->CRH&=0XFFFFFF0F;GPIOE->CRH|=3<<4;}
#define GPIOE_10_OUT_PP() {GPIOE->CRH&=0XFFFFF0FF;GPIOE->CRH|=3<<8;}
#define GPIOE_11_OUT_PP() {GPIOE->CRH&=0XFFFF0FFF;GPIOE->CRH|=3<<12;}
#define GPIOE_12_OUT_PP() {GPIOE->CRH&=0XFFF0FFFF;GPIOE->CRH|=3<<16;}
#define GPIOE_13_OUT_PP() {GPIOE->CRH&=0XFF0FFFFF;GPIOE->CRH|=3<<20;}
#define GPIOE_14_OUT_PP() {GPIOE->CRH&=0XF0FFFFFF;GPIOE->CRH|=3<<24;}
#define GPIOE_15_OUT_PP() {GPIOE->CRH&=0X0FFFFFFF;GPIOE->CRH|=3<<28;}

#define GPIOF_0_OUT_PP()  {GPIOF->CRL&=0XFFFFFFF0;GPIOF->CRL|=3<<0;}
#define GPIOF_1_OUT_PP()  {GPIOF->CRL&=0XFFFFFF0F;GPIOF->CRL|=3<<4;}
#define GPIOF_2_OUT_PP()  {GPIOF->CRL&=0XFFFFF0FF;GPIOF->CRL|=3<<8;}
#define GPIOF_3_OUT_PP()  {GPIOF->CRL&=0XFFFF0FFF;GPIOF->CRL|=3<<12;}
#define GPIOF_4_OUT_PP()  {GPIOF->CRL&=0XFFF0FFFF;GPIOF->CRL|=3<<16;}
#define GPIOF_5_OUT_PP()  {GPIOF->CRL&=0XFF0FFFFF;GPIOF->CRL|=3<<20;}
#define GPIOF_6_OUT_PP()  {GPIOF->CRL&=0XF0FFFFFF;GPIOF->CRL|=3<<24;}
#define GPIOF_7_OUT_PP()  {GPIOF->CRL&=0X0FFFFFFF;GPIOF->CRL|=3<<28;}
#define GPIOF_8_OUT_PP()  {GPIOF->CRH&=0XFFFFFFF0;GPIOF->CRH|=3<<0;}
#define GPIOF_9_OUT_PP()  {GPIOF->CRH&=0XFFFFFF0F;GPIOF->CRH|=3<<4;}
#define GPIOF_10_OUT_PP() {GPIOF->CRH&=0XFFFFF0FF;GPIOF->CRH|=3<<8;}
#define GPIOF_11_OUT_PP() {GPIOF->CRH&=0XFFFF0FFF;GPIOF->CRH|=3<<12;}
#define GPIOF_12_OUT_PP() {GPIOF->CRH&=0XFFF0FFFF;GPIOF->CRH|=3<<16;}
#define GPIOF_13_OUT_PP() {GPIOF->CRH&=0XFF0FFFFF;GPIOF->CRH|=3<<20;}
#define GPIOF_14_OUT_PP() {GPIOF->CRH&=0XF0FFFFFF;GPIOF->CRH|=3<<24;}
#define GPIOF_15_OUT_PP() {GPIOF->CRH&=0X0FFFFFFF;GPIOF->CRH|=3<<28;}

#define GPIOG_0_OUT_PP()  {GPIOG->CRL&=0XFFFFFFF0;GPIOG->CRL|=3<<0;}
#define GPIOG_1_OUT_PP()  {GPIOG->CRL&=0XFFFFFF0F;GPIOG->CRL|=3<<4;}
#define GPIOG_2_OUT_PP()  {GPIOG->CRL&=0XFFFFF0FF;GPIOG->CRL|=3<<8;}
#define GPIOG_3_OUT_PP()  {GPIOG->CRL&=0XFFFF0FFF;GPIOG->CRL|=3<<12;}
#define GPIOG_4_OUT_PP()  {GPIOG->CRL&=0XFFF0FFFF;GPIOG->CRL|=3<<16;}
#define GPIOG_5_OUT_PP()  {GPIOG->CRL&=0XFF0FFFFF;GPIOG->CRL|=3<<20;}
#define GPIOG_6_OUT_PP()  {GPIOG->CRL&=0XF0FFFFFF;GPIOG->CRL|=3<<24;}
#define GPIOG_7_OUT_PP()  {GPIOG->CRL&=0X0FFFFFFF;GPIOG->CRL|=3<<28;}
#define GPIOG_8_OUT_PP()  {GPIOG->CRH&=0XFFFFFFF0;GPIOG->CRH|=3<<0;}
#define GPIOG_9_OUT_PP()  {GPIOG->CRH&=0XFFFFFF0F;GPIOG->CRH|=3<<4;}
#define GPIOG_10_OUT_PP() {GPIOG->CRH&=0XFFFFF0FF;GPIOG->CRH|=3<<8;}
#define GPIOG_11_OUT_PP() {GPIOG->CRH&=0XFFFF0FFF;GPIOG->CRH|=3<<12;}
#define GPIOG_12_OUT_PP() {GPIOG->CRH&=0XFFF0FFFF;GPIOG->CRH|=3<<16;}
#define GPIOG_13_OUT_PP() {GPIOG->CRH&=0XFF0FFFFF;GPIOG->CRH|=3<<20;}
#define GPIOG_14_OUT_PP() {GPIOG->CRH&=0XF0FFFFFF;GPIOG->CRH|=3<<24;}
#define GPIOG_15_OUT_PP() {GPIOG->CRH&=0X0FFFFFFF;GPIOG->CRH|=3<<28;}


#define GPIOA_0_OUT_AFPP()  {GPIOA->CRL&=0XFFFFFFF0;GPIOA->CRL|=0xB<<0;}
#define GPIOA_1_OUT_AFPP()  {GPIOA->CRL&=0XFFFFFF0F;GPIOA->CRL|=0xB<<4;}
#define GPIOA_2_OUT_AFPP()  {GPIOA->CRL&=0XFFFFF0FF;GPIOA->CRL|=0xB<<8;}
#define GPIOA_3_OUT_AFPP()  {GPIOA->CRL&=0XFFFF0FFF;GPIOA->CRL|=0xB<<12;}
#define GPIOA_4_OUT_AFPP()  {GPIOA->CRL&=0XFFF0FFFF;GPIOA->CRL|=0xB<<16;}
#define GPIOA_5_OUT_AFPP()  {GPIOA->CRL&=0XFF0FFFFF;GPIOA->CRL|=0xB<<20;}
#define GPIOA_6_OUT_AFPP()  {GPIOA->CRL&=0XF0FFFFFF;GPIOA->CRL|=0xB<<24;}
#define GPIOA_7_OUT_AFPP()  {GPIOA->CRL&=0X0FFFFFFF;GPIOA->CRL|=0xB<<28;}
#define GPIOA_8_OUT_AFPP()  {GPIOA->CRH&=0XFFFFFFF0;GPIOA->CRH|=0xB<<0;}
#define GPIOA_9_OUT_AFPP()  {GPIOA->CRH&=0XFFFFFF0F;GPIOA->CRH|=0xB<<4;}
#define GPIOA_10_OUT_AFPP() {GPIOA->CRH&=0XFFFFF0FF;GPIOA->CRH|=0xB<<8;}
#define GPIOA_11_OUT_AFPP() {GPIOA->CRH&=0XFFFF0FFF;GPIOA->CRH|=0xB<<12;}
#define GPIOA_12_OUT_AFPP() {GPIOA->CRH&=0XFFF0FFFF;GPIOA->CRH|=0xB<<16;}
#define GPIOA_13_OUT_AFPP() {GPIOA->CRH&=0XFF0FFFFF;GPIOA->CRH|=0xB<<20;}
#define GPIOA_14_OUT_AFPP() {GPIOA->CRH&=0XF0FFFFFF;GPIOA->CRH|=0xB<<24;}
#define GPIOA_15_OUT_AFPP() {GPIOA->CRH&=0X0FFFFFFF;GPIOA->CRH|=0xB<<28;}

#define GPIOB_0_OUT_AFPP()  {GPIOB->CRL&=0XFFFFFFF0;GPIOB->CRL|=0xB<<0;}
#define GPIOB_1_OUT_AFPP()  {GPIOB->CRL&=0XFFFFFF0F;GPIOB->CRL|=0xB<<4;}
#define GPIOB_2_OUT_AFPP()  {GPIOB->CRL&=0XFFFFF0FF;GPIOB->CRL|=0xB<<8;}
#define GPIOB_3_OUT_AFPP()  {GPIOB->CRL&=0XFFFF0FFF;GPIOB->CRL|=0xB<<12;}
#define GPIOB_4_OUT_AFPP()  {GPIOB->CRL&=0XFFF0FFFF;GPIOB->CRL|=0xB<<16;}
#define GPIOB_5_OUT_AFPP()  {GPIOB->CRL&=0XFF0FFFFF;GPIOB->CRL|=0xB<<20;}
#define GPIOB_6_OUT_AFPP()  {GPIOB->CRL&=0XF0FFFFFF;GPIOB->CRL|=0xB<<24;}
#define GPIOB_7_OUT_AFPP()  {GPIOB->CRL&=0X0FFFFFFF;GPIOB->CRL|=0xB<<28;}
#define GPIOB_8_OUT_AFPP()  {GPIOB->CRH&=0XFFFFFFF0;GPIOB->CRH|=0xB<<0;}
#define GPIOB_9_OUT_AFPP()  {GPIOB->CRH&=0XFFFFFF0F;GPIOB->CRH|=0xB<<4;}
#define GPIOB_10_OUT_AFPP() {GPIOB->CRH&=0XFFFFF0FF;GPIOB->CRH|=0xB<<8;}
#define GPIOB_11_OUT_AFPP() {GPIOB->CRH&=0XFFFF0FFF;GPIOB->CRH|=0xB<<12;}
#define GPIOB_12_OUT_AFPP() {GPIOB->CRH&=0XFFF0FFFF;GPIOB->CRH|=0xB<<16;}
#define GPIOB_13_OUT_AFPP() {GPIOB->CRH&=0XFF0FFFFF;GPIOB->CRH|=0xB<<20;}
#define GPIOB_14_OUT_AFPP() {GPIOB->CRH&=0XF0FFFFFF;GPIOB->CRH|=0xB<<24;}
#define GPIOB_15_OUT_AFPP() {GPIOB->CRH&=0X0FFFFFFF;GPIO->CRH|=0xB<<28;}


#define GPIOC_0_OUT_AFPP()  {GPIOC->CRL&=0XFFFFFFF0;GPIOC->CRL|=0xB<<0;}
#define GPIOC_1_OUT_AFPP()  {GPIOC->CRL&=0XFFFFFF0F;GPIOC->CRL|=0xB<<4;}
#define GPIOC_2_OUT_AFPP()  {GPIOC->CRL&=0XFFFFF0FF;GPIOC->CRL|=0xB<<8;}
#define GPIOC_3_OUT_AFPP()  {GPIOC->CRL&=0XFFFF0FFF;GPIOC->CRL|=0xB<<12;}
#define GPIOC_4_OUT_AFPP()  {GPIOC->CRL&=0XFFF0FFFF;GPIOC->CRL|=0xB<<16;}
#define GPIOC_5_OUT_AFPP()  {GPIOC->CRL&=0XFF0FFFFF;GPIOC->CRL|=0xB<<20;}
#define GPIOC_6_OUT_AFPP()  {GPIOC->CRL&=0XF0FFFFFF;GPIOC->CRL|=0xB<<24;}
#define GPIOC_7_OUT_AFPP()  {GPIOC->CRL&=0X0FFFFFFF;GPIOC->CRL|=0xB<<28;}
#define GPIOC_8_OUT_AFPP()  {GPIOC->CRH&=0XFFFFFFF0;GPIOC->CRH|=0xB<<0;}
#define GPIOC_9_OUT_AFPP()  {GPIOC->CRH&=0XFFFFFF0F;GPIOC->CRH|=0xB<<4;}
#define GPIOC_10_OUT_AFPP() {GPIOC->CRH&=0XFFFFF0FF;GPIOC->CRH|=0xB<<8;}
#define GPIOC_11_OUT_AFPP() {GPIOC->CRH&=0XFFFF0FFF;GPIOC->CRH|=0xB<<12;}
#define GPIOC_12_OUT_AFPP() {GPIOC->CRH&=0XFFF0FFFF;GPIOC->CRH|=0xB<<16;}
#define GPIOC_13_OUT_AFPP() {GPIOC->CRH&=0XFF0FFFFF;GPIOC->CRH|=0xB<<20;}
#define GPIOC_14_OUT_AFPP() {GPIOC->CRH&=0XF0FFFFFF;GPIOC->CRH|=0xB<<24;}
#define GPIOC_15_OUT_AFPP() {GPIOC->CRH&=0X0FFFFFFF;GPIOC->CRH|=0xB<<28;}


#define GPIOD_0_OUT_AFPP()  {GPIOD->CRL&=0XFFFFFFF0;GPIOD->CRL|=0xB<<0;}
#define GPIOD_1_OUT_AFPP()  {GPIOD->CRL&=0XFFFFFF0F;GPIOD->CRL|=0xB<<4;}
#define GPIOD_2_OUT_AFPP()  {GPIOD->CRL&=0XFFFFF0FF;GPIOD->CRL|=0xB<<8;}
#define GPIOD_3_OUT_AFPP()  {GPIOD->CRL&=0XFFFF0FFF;GPIOD->CRL|=0xB<<12;}
#define GPIOD_4_OUT_AFPP()  {GPIOD->CRL&=0XFFF0FFFF;GPIOD->CRL|=0xB<<16;}
#define GPIOD_5_OUT_AFPP()  {GPIOD->CRL&=0XFF0FFFFF;GPIOD->CRL|=0xB<<20;}
#define GPIOD_6_OUT_AFPP()  {GPIOD->CRL&=0XF0FFFFFF;GPIOD->CRL|=0xB<<24;}
#define GPIOD_7_OUT_AFPP()  {GPIOD->CRL&=0X0FFFFFFF;GPIOD->CRL|=0xB<<28;}
#define GPIOD_8_OUT_AFPP()  {GPIOD->CRH&=0XFFFFFFF0;GPIOD->CRH|=0xB<<0;}
#define GPIOD_9_OUT_AFPP()  {GPIOD->CRH&=0XFFFFFF0F;GPIOD->CRH|=0xB<<4;}
#define GPIOD_10_OUT_AFPP() {GPIOD->CRH&=0XFFFFF0FF;GPIOD->CRH|=0xB<<8;}
#define GPIOD_11_OUT_AFPP() {GPIOD->CRH&=0XFFFF0FFF;GPIOD->CRH|=0xB<<12;}
#define GPIOD_12_OUT_AFPP() {GPIOD->CRH&=0XFFF0FFFF;GPIOD->CRH|=0xB<<16;}
#define GPIOD_13_OUT_AFPP() {GPIOD->CRH&=0XFF0FFFFF;GPIOD->CRH|=0xB<<20;}
#define GPIOD_14_OUT_AFPP() {GPIOD->CRH&=0XF0FFFFFF;GPIOD->CRH|=0xB<<24;}
#define GPIOD_15_OUT_AFPP() {GPIOD->CRH&=0X0FFFFFFF;GPIOD->CRH|=0xB<<28;}


#define GPIOE_0_OUT_AFPP()  {GPIOE->CRL&=0XFFFFFFF0;GPIOE->CRL|=0xB<<0;}
#define GPIOE_1_OUT_AFPP()  {GPIOE->CRL&=0XFFFFFF0F;GPIOE->CRL|=0xB<<4;}
#define GPIOE_2_OUT_AFPP()  {GPIOE->CRL&=0XFFFFF0FF;GPIOE->CRL|=0xB<<8;}
#define GPIOE_3_OUT_AFPP()  {GPIOE->CRL&=0XFFFF0FFF;GPIOE->CRL|=0xB<<12;}
#define GPIOE_4_OUT_AFPP()  {GPIOE->CRL&=0XFFF0FFFF;GPIOE->CRL|=0xB<<16;}
#define GPIOE_5_OUT_AFPP()  {GPIOE->CRL&=0XFF0FFFFF;GPIOE->CRL|=0xB<<20;}
#define GPIOE_6_OUT_AFPP()  {GPIOE->CRL&=0XF0FFFFFF;GPIOE->CRL|=0xB<<24;}
#define GPIOE_7_OUT_AFPP()  {GPIOE->CRL&=0X0FFFFFFF;GPIOE->CRL|=0xB<<28;}
#define GPIOE_8_OUT_AFPP()  {GPIOE->CRH&=0XFFFFFFF0;GPIOE->CRH|=0xB<<0;}
#define GPIOE_9_OUT_AFPP()  {GPIOE->CRH&=0XFFFFFF0F;GPIOE->CRH|=0xB<<4;}
#define GPIOE_10_OUT_AFPP() {GPIOE->CRH&=0XFFFFF0FF;GPIOE->CRH|=0xB<<8;}
#define GPIOE_11_OUT_AFPP() {GPIOE->CRH&=0XFFFF0FFF;GPIOE->CRH|=0xB<<12;}
#define GPIOE_12_OUT_AFPP() {GPIOE->CRH&=0XFFF0FFFF;GPIOE->CRH|=0xB<<16;}
#define GPIOE_13_OUT_AFPP() {GPIOE->CRH&=0XFF0FFFFF;GPIOE->CRH|=0xB<<20;}
#define GPIOE_14_OUT_AFPP() {GPIOE->CRH&=0XF0FFFFFF;GPIOE->CRH|=0xB<<24;}
#define GPIOE_15_OUT_AFPP() {GPIOE->CRH&=0X0FFFFFFF;GPIOE->CRH|=0xB<<28;}


#define GPIOF_0_OUT_AFPP()  {GPIOF->CRL&=0XFFFFFFF0;GPIOF->CRL|=0xB<<0;}
#define GPIOF_1_OUT_AFPP()  {GPIOF->CRL&=0XFFFFFF0F;GPIOF->CRL|=0xB<<4;}
#define GPIOF_2_OUT_AFPP()  {GPIOF->CRL&=0XFFFFF0FF;GPIOF->CRL|=0xB<<8;}
#define GPIOF_3_OUT_AFPP()  {GPIOF->CRL&=0XFFFF0FFF;GPIOF->CRL|=0xB<<12;}
#define GPIOF_4_OUT_AFPP()  {GPIOF->CRL&=0XFFF0FFFF;GPIOF->CRL|=0xB<<16;}
#define GPIOF_5_OUT_AFPP()  {GPIOF->CRL&=0XFF0FFFFF;GPIOF->CRL|=0xB<<20;}
#define GPIOF_6_OUT_AFPP()  {GPIOF->CRL&=0XF0FFFFFF;GPIOF->CRL|=0xB<<24;}
#define GPIOF_7_OUT_AFPP()  {GPIOF->CRL&=0X0FFFFFFF;GPIOF->CRL|=0xB<<28;}
#define GPIOF_8_OUT_AFPP()  {GPIOF->CRH&=0XFFFFFFF0;GPIOF->CRH|=0xB<<0;}
#define GPIOF_9_OUT_AFPP()  {GPIOF->CRH&=0XFFFFFF0F;GPIOF->CRH|=0xB<<4;}
#define GPIOF_10_OUT_AFPP() {GPIOF->CRH&=0XFFFFF0FF;GPIOF->CRH|=0xB<<8;}
#define GPIOF_11_OUT_AFPP() {GPIOF->CRH&=0XFFFF0FFF;GPIOF->CRH|=0xB<<12;}
#define GPIOF_12_OUT_AFPP() {GPIOF->CRH&=0XFFF0FFFF;GPIOF->CRH|=0xB<<16;}
#define GPIOF_13_OUT_AFPP() {GPIOF->CRH&=0XFF0FFFFF;GPIOF->CRH|=0xB<<20;}
#define GPIOF_14_OUT_AFPP() {GPIOF->CRH&=0XF0FFFFFF;GPIOF->CRH|=0xB<<24;}
#define GPIOF_15_OUT_AFPP() {GPIOF->CRH&=0X0FFFFFFF;GPIOF->CRH|=0xB<<28;}


#define GPIOG_0_OUT_AFPP()  {GPIOG->CRL&=0XFFFFFFF0;GPIOG->CRL|=0xB<<0;}
#define GPIOG_1_OUT_AFPP()  {GPIOG->CRL&=0XFFFFFF0F;GPIOG->CRL|=0xB<<4;}
#define GPIOG_2_OUT_AFPP()  {GPIOG->CRL&=0XFFFFF0FF;GPIOG->CRL|=0xB<<8;}
#define GPIOG_3_OUT_AFPP()  {GPIOG->CRL&=0XFFFF0FFF;GPIOG->CRL|=0xB<<12;}
#define GPIOG_4_OUT_AFPP()  {GPIOG->CRL&=0XFFF0FFFF;GPIOG->CRL|=0xB<<16;}
#define GPIOG_5_OUT_AFPP()  {GPIOG->CRL&=0XFF0FFFFF;GPIOG->CRL|=0xB<<20;}
#define GPIOG_6_OUT_AFPP()  {GPIOG->CRL&=0XF0FFFFFF;GPIOG->CRL|=0xB<<24;}
#define GPIOG_7_OUT_AFPP()  {GPIOG->CRL&=0X0FFFFFFF;GPIOG->CRL|=0xB<<28;}
#define GPIOG_8_OUT_AFPP()  {GPIOG->CRH&=0XFFFFFFF0;GPIOG->CRH|=0xB<<0;}
#define GPIOG_9_OUT_AFPP()  {GPIOG->CRH&=0XFFFFFF0F;GPIOG->CRH|=0xB<<4;}
#define GPIOG_10_OUT_AFPP() {GPIOG->CRH&=0XFFFFF0FF;GPIOG->CRH|=0xB<<8;}
#define GPIOG_11_OUT_AFPP() {GPIOG->CRH&=0XFFFF0FFF;GPIOG->CRH|=0xB<<12;}
#define GPIOG_12_OUT_AFPP() {GPIOG->CRH&=0XFFF0FFFF;GPIOG->CRH|=0xB<<16;}
#define GPIOG_13_OUT_AFPP() {GPIOG->CRH&=0XFF0FFFFF;GPIOG->CRH|=0xB<<20;}
#define GPIOG_14_OUT_AFPP() {GPIOG->CRH&=0XF0FFFFFF;GPIOG->CRH|=0xB<<24;}
#define GPIOG_15_OUT_AFPP() {GPIOG->CRH&=0X0FFFFFFF;GPIOG->CRH|=0xB<<28;}



#define GPIOA_0_IN_UP()  {GPIOA->CRL&=0XFFFFFFF0; GPIOA->CRL|=8<<0;  GPIOA->ODR|=1<<0;}
#define GPIOA_1_IN_UP()  {GPIOA->CRL&=0XFFFFFF0F; GPIOA->CRL|=8<<4;  GPIOA->ODR|=1<<1;}
#define GPIOA_2_IN_UP()  {GPIOA->CRL&=0XFFFFF0FF; GPIOA->CRL|=8<<8;  GPIOA->ODR|=1<<2;}
#define GPIOA_3_IN_UP()  {GPIOA->CRL&=0XFFFF0FFF; GPIOA->CRL|=8<<12; GPIOA->ODR|=1<<3;}
#define GPIOA_4_IN_UP()  {GPIOA->CRL&=0XFFF0FFFF; GPIOA->CRL|=8<<16; GPIOA->ODR|=1<<4;}
#define GPIOA_5_IN_UP()  {GPIOA->CRL&=0XFF0FFFFF; GPIOA->CRL|=8<<20; GPIOA->ODR|=1<<5;}
#define GPIOA_6_IN_UP()  {GPIOA->CRL&=0XF0FFFFFF; GPIOA->CRL|=8<<24; GPIOA->ODR|=1<<6;}
#define GPIOA_7_IN_UP()  {GPIOA->CRL&=0X0FFFFFFF; GPIOA->CRL|=8<<28; GPIOA->ODR|=1<<7;}
#define GPIOA_8_IN_UP()  {GPIOA->CRH&=0XFFFFFFF0; GPIOA->CRH|=8<<0;  GPIOA->ODR|=1<<8;}
#define GPIOA_9_IN_UP()  {GPIOA->CRH&=0XFFFFFF0F; GPIOA->CRH|=8<<4;  GPIOA->ODR|=1<<9;}
#define GPIOA_10_IN_UP() {GPIOA->CRH&=0XFFFFF0FF; GPIOA->CRH|=8<<8;  GPIOA->ODR|=1<<10;}
#define GPIOA_11_IN_UP() {GPIOA->CRH&=0XFFFF0FFF; GPIOA->CRH|=8<<12; GPIOA->ODR|=1<<11;}
#define GPIOA_12_IN_UP() {GPIOA->CRH&=0XFFF0FFFF; GPIOA->CRH|=8<<16; GPIOA->ODR|=1<<12;}
#define GPIOA_13_IN_UP() {GPIOA->CRH&=0XFF0FFFFF; GPIOA->CRH|=8<<20; GPIOA->ODR|=1<<13;}
#define GPIOA_14_IN_UP() {GPIOA->CRH&=0XF0FFFFFF; GPIOA->CRH|=8<<24; GPIOA->ODR|=1<<14;}
#define GPIOA_15_IN_UP() {GPIOA->CRH&=0X0FFFFFFF; GPIOA->CRH|=8<<28; GPIOA->ODR|=1<<15;}

#define GPIOB_0_IN_UP()  {GPIOB->CRL&=0XFFFFFFF0; GPIOB->CRL|=8<<0;  GPIOB->ODR|=1<<0;}
#define GPIOB_1_IN_UP()  {GPIOB->CRL&=0XFFFFFF0F; GPIOB->CRL|=8<<4;  GPIOB->ODR|=1<<1;}
#define GPIOB_2_IN_UP()  {GPIOB->CRL&=0XFFFFF0FF; GPIOB->CRL|=8<<8;  GPIOB->ODR|=1<<2;}
#define GPIOB_3_IN_UP()  {GPIOB->CRL&=0XFFFF0FFF; GPIOB->CRL|=8<<12; GPIOB->ODR|=1<<3;}
#define GPIOB_4_IN_UP()  {GPIOB->CRL&=0XFFF0FFFF; GPIOB->CRL|=8<<16; GPIOB->ODR|=1<<4;}
#define GPIOB_5_IN_UP()  {GPIOB->CRL&=0XFF0FFFFF; GPIOB->CRL|=8<<20; GPIOB->ODR|=1<<5;}
#define GPIOB_6_IN_UP()  {GPIOB->CRL&=0XF0FFFFFF; GPIOB->CRL|=8<<24; GPIOB->ODR|=1<<6;}
#define GPIOB_7_IN_UP()  {GPIOB->CRL&=0X0FFFFFFF; GPIOB->CRL|=8<<28; GPIOB->ODR|=1<<7;}
#define GPIOB_8_IN_UP()  {GPIOB->CRH&=0XFFFFFFF0; GPIOB->CRH|=8<<0;  GPIOB->ODR|=1<<8;}
#define GPIOB_9_IN_UP()  {GPIOB->CRH&=0XFFFFFF0F; GPIOB->CRH|=8<<4;  GPIOB->ODR|=1<<9;}
#define GPIOB_10_IN_UP() {GPIOB->CRH&=0XFFFFF0FF; GPIOB->CRH|=8<<8;  GPIOB->ODR|=1<<10;}
#define GPIOB_11_IN_UP() {GPIOB->CRH&=0XFFFF0FFF; GPIOB->CRH|=8<<12; GPIOB->ODR|=1<<11;}
#define GPIOB_12_IN_UP() {GPIOB->CRH&=0XFFF0FFFF; GPIOB->CRH|=8<<16; GPIOB->ODR|=1<<12;}
#define GPIOB_13_IN_UP() {GPIOB->CRH&=0XFF0FFFFF; GPIOB->CRH|=8<<20; GPIOB->ODR|=1<<13;}
#define GPIOB_14_IN_UP() {GPIOB->CRH&=0XF0FFFFFF; GPIOB->CRH|=8<<24; GPIOB->ODR|=1<<14;}
#define GPIOB_15_IN_UP() {GPIOB->CRH&=0X0FFFFFFF; GPIOB->CRH|=8<<28; GPIOB->ODR|=1<<15;}


#define GPIOC_0_IN_UP()  {GPIOC->CRL&=0XFFFFFFF0; GPIOC->CRL|=8<<0;  GPIOC->ODR|=1<<0;}
#define GPIOC_1_IN_UP()  {GPIOC->CRL&=0XFFFFFF0F; GPIOC->CRL|=8<<4;  GPIOC->ODR|=1<<1;}
#define GPIOC_2_IN_UP()  {GPIOC->CRL&=0XFFFFF0FF; GPIOC->CRL|=8<<8;  GPIOC->ODR|=1<<2;}
#define GPIOC_3_IN_UP()  {GPIOC->CRL&=0XFFFF0FFF; GPIOC->CRL|=8<<12; GPIOC->ODR|=1<<3;}
#define GPIOC_4_IN_UP()  {GPIOC->CRL&=0XFFF0FFFF; GPIOC->CRL|=8<<16; GPIOC->ODR|=1<<4;}
#define GPIOC_5_IN_UP()  {GPIOC->CRL&=0XFF0FFFFF; GPIOC->CRL|=8<<20; GPIOC->ODR|=1<<5;}
#define GPIOC_6_IN_UP()  {GPIOC->CRL&=0XF0FFFFFF; GPIOC->CRL|=8<<24; GPIOC->ODR|=1<<6;}
#define GPIOC_7_IN_UP()  {GPIOC->CRL&=0X0FFFFFFF; GPIOC->CRL|=8<<28; GPIOC->ODR|=1<<7;}
#define GPIOC_8_IN_UP()  {GPIOC->CRH&=0XFFFFFFF0; GPIOC->CRH|=8<<0;  GPIOC->ODR|=1<<8;}
#define GPIOC_9_IN_UP()  {GPIOC->CRH&=0XFFFFFF0F; GPIOC->CRH|=8<<4;  GPIOC->ODR|=1<<9;}
#define GPIOC_10_IN_UP() {GPIOC->CRH&=0XFFFFF0FF; GPIOC->CRH|=8<<8;  GPIOC->ODR|=1<<10;}
#define GPIOC_11_IN_UP() {GPIOC->CRH&=0XFFFF0FFF; GPIOC->CRH|=8<<12; GPIOC->ODR|=1<<11;}
#define GPIOC_12_IN_UP() {GPIOC->CRH&=0XFFF0FFFF; GPIOC->CRH|=8<<16; GPIOC->ODR|=1<<12;}
#define GPIOC_13_IN_UP() {GPIOC->CRH&=0XFF0FFFFF; GPIOC->CRH|=8<<20; GPIOC->ODR|=1<<13;}
#define GPIOC_14_IN_UP() {GPIOC->CRH&=0XF0FFFFFF; GPIOC->CRH|=8<<24; GPIOC->ODR|=1<<14;}
#define GPIOC_15_IN_UP() {GPIOC->CRH&=0X0FFFFFFF; GPIOC->CRH|=8<<28; GPIOC->ODR|=1<<15;}


#define GPIOD_0_IN_UP()  {GPIOD->CRL&=0XFFFFFFF0; GPIOD->CRL|=8<<0;  GPIOD->ODR|=1<<0;}
#define GPIOD_1_IN_UP()  {GPIOD->CRL&=0XFFFFFF0F; GPIOD->CRL|=8<<4;  GPIOD->ODR|=1<<1;}
#define GPIOD_2_IN_UP()  {GPIOD->CRL&=0XFFFFF0FF; GPIOD->CRL|=8<<8;  GPIOD->ODR|=1<<2;}
#define GPIOD_3_IN_UP()  {GPIOD->CRL&=0XFFFF0FFF; GPIOD->CRL|=8<<12; GPIOD->ODR|=1<<3;}
#define GPIOD_4_IN_UP()  {GPIOD->CRL&=0XFFF0FFFF; GPIOD->CRL|=8<<16; GPIOD->ODR|=1<<4;}
#define GPIOD_5_IN_UP()  {GPIOD->CRL&=0XFF0FFFFF; GPIOD->CRL|=8<<20; GPIOD->ODR|=1<<5;}
#define GPIOD_6_IN_UP()  {GPIOD->CRL&=0XF0FFFFFF; GPIOD->CRL|=8<<24; GPIOD->ODR|=1<<6;}
#define GPIOD_7_IN_UP()  {GPIOD->CRL&=0X0FFFFFFF; GPIOD->CRL|=8<<28; GPIOD->ODR|=1<<7;}
#define GPIOD_8_IN_UP()  {GPIOD->CRH&=0XFFFFFFF0; GPIOD->CRH|=8<<0;  GPIOD->ODR|=1<<8;}
#define GPIOD_9_IN_UP()  {GPIOD->CRH&=0XFFFFFF0F; GPIOD->CRH|=8<<4;  GPIOD->ODR|=1<<9;}
#define GPIOD_10_IN_UP() {GPIOD->CRH&=0XFFFFF0FF; GPIOD->CRH|=8<<8;  GPIOD->ODR|=1<<10;}
#define GPIOD_11_IN_UP() {GPIOD->CRH&=0XFFFF0FFF; GPIOD->CRH|=8<<12; GPIOD->ODR|=1<<11;}
#define GPIOD_12_IN_UP() {GPIOD->CRH&=0XFFF0FFFF; GPIOD->CRH|=8<<16; GPIOD->ODR|=1<<12;}
#define GPIOD_13_IN_UP() {GPIOD->CRH&=0XFF0FFFFF; GPIOD->CRH|=8<<20; GPIOD->ODR|=1<<13;}
#define GPIOD_14_IN_UP() {GPIOD->CRH&=0XF0FFFFFF; GPIOD->CRH|=8<<24; GPIOD->ODR|=1<<14;}
#define GPIOD_15_IN_UP() {GPIOD->CRH&=0X0FFFFFFF; GPIOD->CRH|=8<<28; GPIOD->ODR|=1<<15;}


#define GPIOE_0_IN_UP()  {GPIOE->CRL&=0XFFFFFFF0; GPIOE->CRL|=8<<0;  GPIOE->ODR|=1<<0;}
#define GPIOE_1_IN_UP()  {GPIOE->CRL&=0XFFFFFF0F; GPIOE->CRL|=8<<4;  GPIOE->ODR|=1<<1;}
#define GPIOE_2_IN_UP()  {GPIOE->CRL&=0XFFFFF0FF; GPIOE->CRL|=8<<8;  GPIOE->ODR|=1<<2;}
#define GPIOE_3_IN_UP()  {GPIOE->CRL&=0XFFFF0FFF; GPIOE->CRL|=8<<12; GPIOE->ODR|=1<<3;}
#define GPIOE_4_IN_UP()  {GPIOE->CRL&=0XFFF0FFFF; GPIOE->CRL|=8<<16; GPIOE->ODR|=1<<4;}
#define GPIOE_5_IN_UP()  {GPIOE->CRL&=0XFF0FFFFF; GPIOE->CRL|=8<<20; GPIOE->ODR|=1<<5;}
#define GPIOE_6_IN_UP()  {GPIOE->CRL&=0XF0FFFFFF; GPIOE->CRL|=8<<24; GPIOE->ODR|=1<<6;}
#define GPIOE_7_IN_UP()  {GPIOE->CRL&=0X0FFFFFFF; GPIOE->CRL|=8<<28; GPIOE->ODR|=1<<7;}
#define GPIOE_8_IN_UP()  {GPIOE->CRH&=0XFFFFFFF0; GPIOE->CRH|=8<<0;  GPIOE->ODR|=1<<8;}
#define GPIOE_9_IN_UP()  {GPIOE->CRH&=0XFFFFFF0F; GPIOE->CRH|=8<<4;  GPIOE->ODR|=1<<9;}
#define GPIOE_10_IN_UP() {GPIOE->CRH&=0XFFFFF0FF; GPIOE->CRH|=8<<8;  GPIOE->ODR|=1<<10;}
#define GPIOE_11_IN_UP() {GPIOE->CRH&=0XFFFF0FFF; GPIOE->CRH|=8<<12; GPIOE->ODR|=1<<11;}
#define GPIOE_12_IN_UP() {GPIOE->CRH&=0XFFF0FFFF; GPIOE->CRH|=8<<16; GPIOE->ODR|=1<<12;}
#define GPIOE_13_IN_UP() {GPIOE->CRH&=0XFF0FFFFF; GPIOE->CRH|=8<<20; GPIOE->ODR|=1<<13;}
#define GPIOE_14_IN_UP() {GPIOE->CRH&=0XF0FFFFFF; GPIOE->CRH|=8<<24; GPIOE->ODR|=1<<14;}
#define GPIOE_15_IN_UP() {GPIOE->CRH&=0X0FFFFFFF; GPIOE->CRH|=8<<28; GPIOE->ODR|=1<<15;}


#define GPIOF_0_IN_UP()  {GPIOF->CRL&=0XFFFFFFF0; GPIOF->CRL|=8<<0;  GPIOF->ODR|=1<<0;}
#define GPIOF_1_IN_UP()  {GPIOF->CRL&=0XFFFFFF0F; GPIOF->CRL|=8<<4;  GPIOF->ODR|=1<<1;}
#define GPIOF_2_IN_UP()  {GPIOF->CRL&=0XFFFFF0FF; GPIOF->CRL|=8<<8;  GPIOF->ODR|=1<<2;}
#define GPIOF_3_IN_UP()  {GPIOF->CRL&=0XFFFF0FFF; GPIOF->CRL|=8<<12; GPIOF->ODR|=1<<3;}
#define GPIOF_4_IN_UP()  {GPIOF->CRL&=0XFFF0FFFF; GPIOF->CRL|=8<<16; GPIOF->ODR|=1<<4;}
#define GPIOF_5_IN_UP()  {GPIOF->CRL&=0XFF0FFFFF; GPIOF->CRL|=8<<20; GPIOF->ODR|=1<<5;}
#define GPIOF_6_IN_UP()  {GPIOF->CRL&=0XF0FFFFFF; GPIOF->CRL|=8<<24; GPIOF->ODR|=1<<6;}
#define GPIOF_7_IN_UP()  {GPIOF->CRL&=0X0FFFFFFF; GPIOF->CRL|=8<<28; GPIOF->ODR|=1<<7;}
#define GPIOF_8_IN_UP()  {GPIOF->CRH&=0XFFFFFFF0; GPIOF->CRH|=8<<0;  GPIOF->ODR|=1<<8;}
#define GPIOF_9_IN_UP()  {GPIOF->CRH&=0XFFFFFF0F; GPIOF->CRH|=8<<4;  GPIOF->ODR|=1<<9;}
#define GPIOF_10_IN_UP() {GPIOF->CRH&=0XFFFFF0FF; GPIOF->CRH|=8<<8;  GPIOF->ODR|=1<<10;}
#define GPIOF_11_IN_UP() {GPIOF->CRH&=0XFFFF0FFF; GPIOF->CRH|=8<<12; GPIOF->ODR|=1<<11;}
#define GPIOF_12_IN_UP() {GPIOF->CRH&=0XFFF0FFFF; GPIOF->CRH|=8<<16; GPIOF->ODR|=1<<12;}
#define GPIOF_13_IN_UP() {GPIOF->CRH&=0XFF0FFFFF; GPIOF->CRH|=8<<20; GPIOF->ODR|=1<<13;}
#define GPIOF_14_IN_UP() {GPIOF->CRH&=0XF0FFFFFF; GPIOF->CRH|=8<<24; GPIOF->ODR|=1<<14;}
#define GPIOF_15_IN_UP() {GPIOF->CRH&=0X0FFFFFFF; GPIOF->CRH|=8<<28; GPIOFF->ODR|=1<<15;}


#define GPIOG_0_IN_UP()  {GPIOG->CRL&=0XFFFFFFF0; GPIOG->CRL|=8<<0;  GPIOG->ODR|=1<<0;}
#define GPIOG_1_IN_UP()  {GPIOG->CRL&=0XFFFFFF0F; GPIOG->CRL|=8<<4;  GPIOG->ODR|=1<<1;}
#define GPIOG_2_IN_UP()  {GPIOG->CRL&=0XFFFFF0FF; GPIOG->CRL|=8<<8;  GPIOG->ODR|=1<<2;}
#define GPIOG_3_IN_UP()  {GPIOG->CRL&=0XFFFF0FFF; GPIOG->CRL|=8<<12; GPIOG->ODR|=1<<3;}
#define GPIOG_4_IN_UP()  {GPIOG->CRL&=0XFFF0FFFF; GPIOG->CRL|=8<<16; GPIOG->ODR|=1<<4;}
#define GPIOG_5_IN_UP()  {GPIOG->CRL&=0XFF0FFFFF; GPIOG->CRL|=8<<20; GPIOG->ODR|=1<<5;}
#define GPIOG_6_IN_UP()  {GPIOG->CRL&=0XF0FFFFFF; GPIOG->CRL|=8<<24; GPIOG->ODR|=1<<6;}
#define GPIOG_7_IN_UP()  {GPIOG->CRL&=0X0FFFFFFF; GPIOG->CRL|=8<<28; GPIOG->ODR|=1<<7;}
#define GPIOG_8_IN_UP()  {GPIOG->CRH&=0XFFFFFFF0; GPIOG->CRH|=8<<0;  GPIOG->ODR|=1<<8;}
#define GPIOG_9_IN_UP()  {GPIOG->CRH&=0XFFFFFF0F; GPIOG->CRH|=8<<4;  GPIOG->ODR|=1<<9;}
#define GPIOG_10_IN_UP() {GPIOG->CRH&=0XFFFFF0FF; GPIOG->CRH|=8<<8;  GPIOG->ODR|=1<<10;}
#define GPIOG_11_IN_UP() {GPIOG->CRH&=0XFFFF0FFF; GPIOG->CRH|=8<<12; GPIOG->ODR|=1<<11;}
#define GPIOG_12_IN_UP() {GPIOG->CRH&=0XFFF0FFFF; GPIOG->CRH|=8<<16; GPIOG->ODR|=1<<12;}
#define GPIOG_13_IN_UP() {GPIOG->CRH&=0XFF0FFFFF; GPIOG->CRH|=8<<20; GPIOG->ODR|=1<<13;}
#define GPIOG_14_IN_UP() {GPIOG->CRH&=0XF0FFFFFF; GPIOG->CRH|=8<<24; GPIOG->ODR|=1<<14;}
#define GPIOG_15_IN_UP() {GPIOG->CRH&=0X0FFFFFFF; GPIOG->CRH|=8<<28; GPIOG->ODR|=1<<15;}



#define GPIOA_0_IN_DOWN()  {GPIOA->CRL&=0XFFFFFFF0; GPIOA->CRL|=8<<0;  GPIOA->ODR&=0xFFFE;}
#define GPIOA_1_IN_DOWN()  {GPIOA->CRL&=0XFFFFFF0F; GPIOA->CRL|=8<<4;  GPIOA->ODR&=0xFFFD;}
#define GPIOA_2_IN_DOWN()  {GPIOA->CRL&=0XFFFFF0FF; GPIOA->CRL|=8<<8;  GPIOA->ODR&=0xFFFB;}
#define GPIOA_3_IN_DOWN()  {GPIOA->CRL&=0XFFFF0FFF; GPIOA->CRL|=8<<12; GPIOA->ODR&=0xFFF7;}
#define GPIOA_4_IN_DOWN()  {GPIOA->CRL&=0XFFF0FFFF; GPIOA->CRL|=8<<16; GPIOA->ODR&=0xFFEF;}
#define GPIOA_5_IN_DOWN()  {GPIOA->CRL&=0XFF0FFFFF; GPIOA->CRL|=8<<20; GPIOA->ODR&=0xFFDF;}
#define GPIOA_6_IN_DOWN()  {GPIOA->CRL&=0XF0FFFFFF; GPIOA->CRL|=8<<24; GPIOA->ODR&=0xFFBF;}
#define GPIOA_7_IN_DOWN()  {GPIOA->CRL&=0X0FFFFFFF; GPIOA->CRL|=8<<28; GPIOA->ODR&=0xFF7F;}
#define GPIOA_8_IN_DOWN()  {GPIOA->CRH&=0XFFFFFFF0; GPIOA->CRH|=8<<0;  GPIOA->ODR&=0xFEFF;}
#define GPIOA_9_IN_DOWN()  {GPIOA->CRH&=0XFFFFFF0F; GPIOA->CRH|=8<<4;  GPIOA->ODR&=0xFDFF;}
#define GPIOA_10_IN_DOWN() {GPIOA->CRH&=0XFFFFF0FF; GPIOA->CRH|=8<<8;  GPIOA->ODR&=0xFBFF;}
#define GPIOA_11_IN_DOWN() {GPIOA->CRH&=0XFFFF0FFF; GPIOA->CRH|=8<<12; GPIOA->ODR&=0xF7FF;}
#define GPIOA_12_IN_DOWN() {GPIOA->CRH&=0XFFF0FFFF; GPIOA->CRH|=8<<16; GPIOA->ODR&=0xEFFF;}
#define GPIOA_13_IN_DOWN() {GPIOA->CRH&=0XFF0FFFFF; GPIOA->CRH|=8<<20; GPIOA->ODR&=0xDFFF;}
#define GPIOA_14_IN_DOWN() {GPIOA->CRH&=0XF0FFFFFF; GPIOA->CRH|=8<<24; GPIOA->ODR&=0xBFFF;}
#define GPIOA_15_IN_DOWN() {GPIOA->CRH&=0X0FFFFFFF; GPIOA->CRH|=8<<28; GPIOA->ODR&=0x7FFF;}

#define GPIOB_0_IN_DOWN()  {GPIO8->CRL&=0XFFFFFFF0; GPIO8->CRL|=8<<0;  GPIOB->ODR&=0xFFFE;}
#define GPIOB_1_IN_DOWN()  {GPIO8->CRL&=0XFFFFFF0F; GPIO8->CRL|=8<<4;  GPIOB->ODR&=0xFFFD;}
#define GPIOB_2_IN_DOWN()  {GPIO8->CRL&=0XFFFFF0FF; GPIO8->CRL|=8<<8;  GPIOB->ODR&=0xFFFB;}
#define GPIOB_3_IN_DOWN()  {GPIO8->CRL&=0XFFFF0FFF; GPIO8->CRL|=8<<12; GPIOB->ODR&=0xFFF7;}
#define GPIOB_4_IN_DOWN()  {GPIO8->CRL&=0XFFF0FFFF; GPIO8->CRL|=8<<16; GPIOB->ODR&=0xFFEF;}
#define GPIOB_5_IN_DOWN()  {GPIO8->CRL&=0XFF0FFFFF; GPIO8->CRL|=8<<20; GPIOB->ODR&=0xFFDF;}
#define GPIOB_6_IN_DOWN()  {GPIO8->CRL&=0XF0FFFFFF; GPIO8->CRL|=8<<24; GPIOB->ODR&=0xFFBF;}
#define GPIOB_7_IN_DOWN()  {GPIO8->CRL&=0X0FFFFFFF; GPIO8->CRL|=8<<28; GPIOB->ODR&=0xFF7F;}
#define GPIOB_8_IN_DOWN()  {GPIO8->CRH&=0XFFFFFFF0; GPIO8->CRH|=8<<0;  GPIOB->ODR&=0xFEFF;}
#define GPIOB_9_IN_DOWN()  {GPIO8->CRH&=0XFFFFFF0F; GPIO8->CRH|=8<<4;  GPIOB->ODR&=0xFDFF;}
#define GPIOB_10_IN_DOWN() {GPIO8->CRH&=0XFFFFF0FF; GPIO8->CRH|=8<<8;  GPIOB->ODR&=0xFBFF;}
#define GPIOB_11_IN_DOWN() {GPIO8->CRH&=0XFFFF0FFF; GPIO8->CRH|=8<<12; GPIOB->ODR&=0xF7FF;}
#define GPIOB_12_IN_DOWN() {GPIO8->CRH&=0XFFF0FFFF; GPIO8->CRH|=8<<16; GPIOB->ODR&=0xEFFF;}
#define GPIOB_13_IN_DOWN() {GPIO8->CRH&=0XFF0FFFFF; GPIO8->CRH|=8<<20; GPIOB->ODR&=0xDFFF;}
#define GPIOB_14_IN_DOWN() {GPIO8->CRH&=0XF0FFFFFF; GPIO8->CRH|=8<<24; GPIOB->ODR&=0xBFFF;}
#define GPIOB_15_IN_DOWN() {GPIO8->CRH&=0X0FFFFFFF; GPIO8->CRH|=8<<28; GPIOB->ODR&=0x7FFF;}


#define GPIOC_0_IN_DOWN()  {GPIOC->CRL&=0XFFFFFFF0; GPIOC->CRL|=8<<0;  GPIOC->ODR&=0xFFFE;}
#define GPIOC_1_IN_DOWN()  {GPIOC->CRL&=0XFFFFFF0F; GPIOC->CRL|=8<<4;  GPIOC->ODR&=0xFFFD;}
#define GPIOC_2_IN_DOWN()  {GPIOC->CRL&=0XFFFFF0FF; GPIOC->CRL|=8<<8;  GPIOC->ODR&=0xFFFB;}
#define GPIOC_3_IN_DOWN()  {GPIOC->CRL&=0XFFFF0FFF; GPIOC->CRL|=8<<12; GPIOC->ODR&=0xFFF7;}
#define GPIOC_4_IN_DOWN()  {GPIOC->CRL&=0XFFF0FFFF; GPIOC->CRL|=8<<16; GPIOC->ODR&=0xFFEF;}
#define GPIOC_5_IN_DOWN()  {GPIOC->CRL&=0XFF0FFFFF; GPIOC->CRL|=8<<20; GPIOC->ODR&=0xFFDF;}
#define GPIOC_6_IN_DOWN()  {GPIOC->CRL&=0XF0FFFFFF; GPIOC->CRL|=8<<24; GPIOC->ODR&=0xFFBF;}
#define GPIOC_7_IN_DOWN()  {GPIOC->CRL&=0X0FFFFFFF; GPIOC->CRL|=8<<28; GPIOC->ODR&=0xFF7F;}
#define GPIOC_8_IN_DOWN()  {GPIOC->CRH&=0XFFFFFFF0; GPIOC->CRH|=8<<0;  GPIOC->ODR&=0xFEFF;}
#define GPIOC_9_IN_DOWN()  {GPIOC->CRH&=0XFFFFFF0F; GPIOC->CRH|=8<<4;  GPIOC->ODR&=0xFDFF;}
#define GPIOC_10_IN_DOWN() {GPIOC->CRH&=0XFFFFF0FF; GPIOC->CRH|=8<<8;  GPIOC->ODR&=0xFBFF;}
#define GPIOC_11_IN_DOWN() {GPIOC->CRH&=0XFFFF0FFF; GPIOC->CRH|=8<<12; GPIOC->ODR&=0xF7FF;}
#define GPIOC_12_IN_DOWN() {GPIOC->CRH&=0XFFF0FFFF; GPIOC->CRH|=8<<16; GPIOC->ODR&=0xEFFF;}
#define GPIOC_13_IN_DOWN() {GPIOC->CRH&=0XFF0FFFFF; GPIOC->CRH|=8<<20; GPIOC->ODR&=0xDFFF;}
#define GPIOC_14_IN_DOWN() {GPIOC->CRH&=0XF0FFFFFF; GPIOC->CRH|=8<<24; GPIOC->ODR&=0xBFFF;}
#define GPIOC_15_IN_DOWN() {GPIOC->CRH&=0X0FFFFFFF; GPIOC->CRH|=8<<28; GPIOC->ODR&=0x7FFF;}


#define GPIOD_0_IN_DOWN()  {GPIOD->CRL&=0XFFFFFFF0; GPIOD->CRL|=8<<0;  GPIOD->ODR&=0xFFFE;}
#define GPIOD_1_IN_DOWN()  {GPIOD->CRL&=0XFFFFFF0F; GPIOD->CRL|=8<<4;  GPIOD->ODR&=0xFFFD;}
#define GPIOD_2_IN_DOWN()  {GPIOD->CRL&=0XFFFFF0FF; GPIOD->CRL|=8<<8;  GPIOD->ODR&=0xFFFB;}
#define GPIOD_3_IN_DOWN()  {GPIOD->CRL&=0XFFFF0FFF; GPIOD->CRL|=8<<12; GPIOD->ODR&=0xFFF7;}
#define GPIOD_4_IN_DOWN()  {GPIOD->CRL&=0XFFF0FFFF; GPIOD->CRL|=8<<16; GPIOD->ODR&=0xFFEF;}
#define GPIOD_5_IN_DOWN()  {GPIOD->CRL&=0XFF0FFFFF; GPIOD->CRL|=8<<20; GPIOD->ODR&=0xFFDF;}
#define GPIOD_6_IN_DOWN()  {GPIOD->CRL&=0XF0FFFFFF; GPIOD->CRL|=8<<24; GPIOD->ODR&=0xFFBF;}
#define GPIOD_7_IN_DOWN()  {GPIOD->CRL&=0X0FFFFFFF; GPIOD->CRL|=8<<28; GPIOD->ODR&=0xFF7F;}
#define GPIOD_8_IN_DOWN()  {GPIOD->CRH&=0XFFFFFFF0; GPIOD->CRH|=8<<0;  GPIOD->ODR&=0xFEFF;}
#define GPIOD_9_IN_DOWN()  {GPIOD->CRH&=0XFFFFFF0F; GPIOD->CRH|=8<<4;  GPIOD->ODR&=0xFDFF;}
#define GPIOD_10_IN_DOWN() {GPIOD->CRH&=0XFFFFF0FF; GPIOD->CRH|=8<<8;  GPIOD->ODR&=0xFBFF;}
#define GPIOD_11_IN_DOWN() {GPIOD->CRH&=0XFFFF0FFF; GPIOD->CRH|=8<<12; GPIOD->ODR&=0xF7FF;}
#define GPIOD_12_IN_DOWN() {GPIOD->CRH&=0XFFF0FFFF; GPIOD->CRH|=8<<16; GPIOD->ODR&=0xEFFF;}
#define GPIOD_13_IN_DOWN() {GPIOD->CRH&=0XFF0FFFFF; GPIOD->CRH|=8<<20; GPIOD->ODR&=0xDFFF;}
#define GPIOD_14_IN_DOWN() {GPIOD->CRH&=0XF0FFFFFF; GPIOD->CRH|=8<<24; GPIOD->ODR&=0xBFFF;}
#define GPIOD_15_IN_DOWN() {GPIOD->CRH&=0X0FFFFFFF; GPIOD->CRH|=8<<28; GPIOD->ODR&=0x7FFF;}


#define GPIOE_0_IN_DOWN()  {GPIOE->CRL&=0XFFFFFFF0; GPIOE->CRL|=8<<0;  GPIOE->ODR&=0xFFFE;}
#define GPIOE_1_IN_DOWN()  {GPIOE->CRL&=0XFFFFFF0F; GPIOE->CRL|=8<<4;  GPIOE->ODR&=0xFFFD;}
#define GPIOE_2_IN_DOWN()  {GPIOE->CRL&=0XFFFFF0FF; GPIOE->CRL|=8<<8;  GPIOE->ODR&=0xFFFB;}
#define GPIOE_3_IN_DOWN()  {GPIOE->CRL&=0XFFFF0FFF; GPIOE->CRL|=8<<12; GPIOE->ODR&=0xFFF7;}
#define GPIOE_4_IN_DOWN()  {GPIOE->CRL&=0XFFF0FFFF; GPIOE->CRL|=8<<16; GPIOE->ODR&=0xFFEF;}
#define GPIOE_5_IN_DOWN()  {GPIOE->CRL&=0XFF0FFFFF; GPIOE->CRL|=8<<20; GPIOE->ODR&=0xFFDF;}
#define GPIOE_6_IN_DOWN()  {GPIOE->CRL&=0XF0FFFFFF; GPIOE->CRL|=8<<24; GPIOE->ODR&=0xFFBF;}
#define GPIOE_7_IN_DOWN()  {GPIOE->CRL&=0X0FFFFFFF; GPIOE->CRL|=8<<28; GPIOE->ODR&=0xFF7F;}
#define GPIOE_8_IN_DOWN()  {GPIOE->CRH&=0XFFFFFFF0; GPIOE->CRH|=8<<0;  GPIOE->ODR&=0xFEFF;}
#define GPIOE_9_IN_DOWN()  {GPIOE->CRH&=0XFFFFFF0F; GPIOE->CRH|=8<<4;  GPIOE->ODR&=0xFDFF;}
#define GPIOE_10_IN_DOWN() {GPIOE->CRH&=0XFFFFF0FF; GPIOE->CRH|=8<<8;  GPIOE->ODR&=0xFBFF;}
#define GPIOE_11_IN_DOWN() {GPIOE->CRH&=0XFFFF0FFF; GPIOE->CRH|=8<<12; GPIOE->ODR&=0xF7FF;}
#define GPIOE_12_IN_DOWN() {GPIOE->CRH&=0XFFF0FFFF; GPIOE->CRH|=8<<16; GPIOE->ODR&=0xEFFF;}
#define GPIOE_13_IN_DOWN() {GPIOE->CRH&=0XFF0FFFFF; GPIOE->CRH|=8<<20; GPIOE->ODR&=0xDFFF;}
#define GPIOE_14_IN_DOWN() {GPIOE->CRH&=0XF0FFFFFF; GPIOE->CRH|=8<<24; GPIOE->ODR&=0xBFFF;}
#define GPIOE_15_IN_DOWN() {GPIOE->CRH&=0X0FFFFFFF; GPIOE->CRH|=8<<28; GPIOE->ODR&=0x7FFF;}


#define GPIOF_0_IN_DOWN()  {GPIOF->CRL&=0XFFFFFFF0; GPIOF->CRL|=8<<0;  GPIOF->ODR&=0xFFFE;}
#define GPIOF_1_IN_DOWN()  {GPIOF->CRL&=0XFFFFFF0F; GPIOF->CRL|=8<<4;  GPIOF->ODR&=0xFFFD;}
#define GPIOF_2_IN_DOWN()  {GPIOF->CRL&=0XFFFFF0FF; GPIOF->CRL|=8<<8;  GPIOF->ODR&=0xFFFB;}
#define GPIOF_3_IN_DOWN()  {GPIOF->CRL&=0XFFFF0FFF; GPIOF->CRL|=8<<12; GPIOF->ODR&=0xFFF7;}
#define GPIOF_4_IN_DOWN()  {GPIOF->CRL&=0XFFF0FFFF; GPIOF->CRL|=8<<16; GPIOF->ODR&=0xFFEF;}
#define GPIOF_5_IN_DOWN()  {GPIOF->CRL&=0XFF0FFFFF; GPIOF->CRL|=8<<20; GPIOF->ODR&=0xFFDF;}
#define GPIOF_6_IN_DOWN()  {GPIOF->CRL&=0XF0FFFFFF; GPIOF->CRL|=8<<24; GPIOF->ODR&=0xFFBF;}
#define GPIOF_7_IN_DOWN()  {GPIOF->CRL&=0X0FFFFFFF; GPIOF->CRL|=8<<28; GPIOF->ODR&=0xFF7F;}
#define GPIOF_8_IN_DOWN()  {GPIOF->CRH&=0XFFFFFFF0; GPIOF->CRH|=8<<0;  GPIOF->ODR&=0xFEFF;}
#define GPIOF_9_IN_DOWN()  {GPIOF->CRH&=0XFFFFFF0F; GPIOF->CRH|=8<<4;  GPIOF->ODR&=0xFDFF;}
#define GPIOF_10_IN_DOWN() {GPIOF->CRH&=0XFFFFF0FF; GPIOF->CRH|=8<<8;  GPIOF->ODR&=0xFBFF;}
#define GPIOF_11_IN_DOWN() {GPIOF->CRH&=0XFFFF0FFF; GPIOF->CRH|=8<<12; GPIOF->ODR&=0xF7FF;}
#define GPIOF_12_IN_DOWN() {GPIOF->CRH&=0XFFF0FFFF; GPIOF->CRH|=8<<16; GPIOF->ODR&=0xEFFF;}
#define GPIOF_13_IN_DOWN() {GPIOF->CRH&=0XFF0FFFFF; GPIOF->CRH|=8<<20; GPIOF->ODR&=0xDFFF;}
#define GPIOF_14_IN_DOWN() {GPIOF->CRH&=0XF0FFFFFF; GPIOF->CRH|=8<<24; GPIOF->ODR&=0xBFFF;}
#define GPIOF_15_IN_DOWN() {GPIOF->CRH&=0X0FFFFFFF; GPIOF->CRH|=8<<28; GPIOF->ODR&=0x7FFF;}


#define GPIOG_0_IN_DOWN()  {GPIOG->CRL&=0XFFFFFFF0; GPIOG->CRL|=8<<0;  GPIOG->ODR&=0xFFFE;}
#define GPIOG_1_IN_DOWN()  {GPIOG->CRL&=0XFFFFFF0F; GPIOG->CRL|=8<<4;  GPIOG->ODR&=0xFFFD;}
#define GPIOG_2_IN_DOWN()  {GPIOG->CRL&=0XFFFFF0FF; GPIOG->CRL|=8<<8;  GPIOG->ODR&=0xFFFB;}
#define GPIOG_3_IN_DOWN()  {GPIOG->CRL&=0XFFFF0FFF; GPIOG->CRL|=8<<12; GPIOG->ODR&=0xFFF7;}
#define GPIOG_4_IN_DOWN()  {GPIOG->CRL&=0XFFF0FFFF; GPIOG->CRL|=8<<16; GPIOG->ODR&=0xFFEF;}
#define GPIOG_5_IN_DOWN()  {GPIOG->CRL&=0XFF0FFFFF; GPIOG->CRL|=8<<20; GPIOG->ODR&=0xFFDF;}
#define GPIOG_6_IN_DOWN()  {GPIOG->CRL&=0XF0FFFFFF; GPIOG->CRL|=8<<24; GPIOG->ODR&=0xFFBF;}
#define GPIOG_7_IN_DOWN()  {GPIOG->CRL&=0X0FFFFFFF; GPIOG->CRL|=8<<28; GPIOG->ODR&=0xFF7F;}
#define GPIOG_8_IN_DOWN()  {GPIOG->CRH&=0XFFFFFFF0; GPIOG->CRH|=8<<0;  GPIOG->ODR&=0xFEFF;}
#define GPIOG_9_IN_DOWN()  {GPIOG->CRH&=0XFFFFFF0F; GPIOG->CRH|=8<<4;  GPIOG->ODR&=0xFDFF;}
#define GPIOG_10_IN_DOWN() {GPIOG->CRH&=0XFFFFF0FF; GPIOG->CRH|=8<<8;  GPIOG->ODR&=0xFBFF;}
#define GPIOG_11_IN_DOWN() {GPIOG->CRH&=0XFFFF0FFF; GPIOG->CRH|=8<<12; GPIOG->ODR&=0xF7FF;}
#define GPIOG_12_IN_DOWN() {GPIOG->CRH&=0XFFF0FFFF; GPIOG->CRH|=8<<16; GPIOG->ODR&=0xEFFF;}
#define GPIOG_13_IN_DOWN() {GPIOG->CRH&=0XFF0FFFFF; GPIOG->CRH|=8<<20; GPIOG->ODR&=0xDFFF;}
#define GPIOG_14_IN_DOWN() {GPIOG->CRH&=0XF0FFFFFF; GPIOG->CRH|=8<<24; GPIOG->ODR&=0xBFFF;}
#define GPIOG_15_IN_DOWN() {GPIOG->CRH&=0X0FFFFFFF; GPIOG->CRH|=8<<28; GPIOG->ODR&=0x7FFF;}


#define GPIOA_0_IN_FLOAT()  {GPIOA->CRL&=0XFFFFFFF0;GPIOA->CRL|=4<<0;}
#define GPIOA_1_IN_FLOAT()  {GPIOA->CRL&=0XFFFFFF0F;GPIOA->CRL|=4<<4;}
#define GPIOA_2_IN_FLOAT()  {GPIOA->CRL&=0XFFFFF0FF;GPIOA->CRL|=4<<8;}
#define GPIOA_3_IN_FLOAT()  {GPIOA->CRL&=0XFFFF0FFF;GPIOA->CRL|=4<<12;}
#define GPIOA_4_IN_FLOAT()  {GPIOA->CRL&=0XFFF0FFFF;GPIOA->CRL|=4<<16;}
#define GPIOA_5_IN_FLOAT()  {GPIOA->CRL&=0XFF0FFFFF;GPIOA->CRL|=4<<20;}
#define GPIOA_6_IN_FLOAT()  {GPIOA->CRL&=0XF0FFFFFF;GPIOA->CRL|=4<<24;}
#define GPIOA_7_IN_FLOAT()  {GPIOA->CRL&=0X0FFFFFFF;GPIOA->CRL|=4<<28;}
#define GPIOA_8_IN_FLOAT()  {GPIOA->CRH&=0XFFFFFFF0;GPIOA->CRH|=4<<0;}
#define GPIOA_9_IN_FLOAT()  {GPIOA->CRH&=0XFFFFFF0F;GPIOA->CRH|=4<<4;}
#define GPIOA_10_IN_FLOAT() {GPIOA->CRH&=0XFFFFF0FF;GPIOA->CRH|=4<<8;}
#define GPIOA_11_IN_FLOAT() {GPIOA->CRH&=0XFFFF0FFF;GPIOA->CRH|=4<<12;}
#define GPIOA_12_IN_FLOAT() {GPIOA->CRH&=0XFFF0FFFF;GPIOA->CRH|=4<<16;}
#define GPIOA_13_IN_FLOAT() {GPIOA->CRH&=0XFF0FFFFF;GPIOA->CRH|=4<<20;}
#define GPIOA_14_IN_FLOAT() {GPIOA->CRH&=0XF0FFFFFF;GPIOA->CRH|=4<<24;}
#define GPIOA_15_IN_FLOAT() {GPIOA->CRH&=0X0FFFFFFF;GPIOA->CRH|=4<<28;}

#define GPIOB_0_IN_FLOAT()  {GPIOB->CRL&=0XFFFFFFF0;GPIOB->CRL|=4<<0;}
#define GPIOB_1_IN_FLOAT()  {GPIOB->CRL&=0XFFFFFF0F;GPIOB->CRL|=4<<4;}
#define GPIOB_2_IN_FLOAT()  {GPIOB->CRL&=0XFFFFF0FF;GPIOB->CRL|=4<<8;}
#define GPIOB_3_IN_FLOAT()  {GPIOB->CRL&=0XFFFF0FFF;GPIOB->CRL|=4<<12;}
#define GPIOB_4_IN_FLOAT()  {GPIOB->CRL&=0XFFF0FFFF;GPIOB->CRL|=4<<16;}
#define GPIOB_5_IN_FLOAT()  {GPIOB->CRL&=0XFF0FFFFF;GPIOB->CRL|=4<<20;}
#define GPIOB_6_IN_FLOAT()  {GPIOB->CRL&=0XF0FFFFFF;GPIOB->CRL|=4<<24;}
#define GPIOB_7_IN_FLOAT()  {GPIOB->CRL&=0X0FFFFFFF;GPIOB->CRL|=4<<28;}
#define GPIOB_8_IN_FLOAT()  {GPIOB->CRH&=0XFFFFFFF0;GPIOB->CRH|=4<<0;}
#define GPIOB_9_IN_FLOAT()  {GPIOB->CRH&=0XFFFFFF0F;GPIOB->CRH|=4<<4;}
#define GPIOB_10_IN_FLOAT() {GPIOB->CRH&=0XFFFFF0FF;GPIOB->CRH|=4<<8;}
#define GPIOB_11_IN_FLOAT() {GPIOB->CRH&=0XFFFF0FFF;GPIOB->CRH|=4<<12;}
#define GPIOB_12_IN_FLOAT() {GPIOB->CRH&=0XFFF0FFFF;GPIOB->CRH|=4<<16;}
#define GPIOB_13_IN_FLOAT() {GPIOB->CRH&=0XFF0FFFFF;GPIOB->CRH|=4<<20;}
#define GPIOB_14_IN_FLOAT() {GPIOB->CRH&=0XF0FFFFFF;GPIOB->CRH|=4<<24;}
#define GPIOB_15_IN_FLOAT() {GPIOB->CRH&=0X0FFFFFFF;GPIO->CRH|=4<<28;}


#define GPIOC_0_IN_FLOAT()  {GPIOC->CRL&=0XFFFFFFF0;GPIOC->CRL|=4<<0;}
#define GPIOC_1_IN_FLOAT()  {GPIOC->CRL&=0XFFFFFF0F;GPIOC->CRL|=4<<4;}
#define GPIOC_2_IN_FLOAT()  {GPIOC->CRL&=0XFFFFF0FF;GPIOC->CRL|=4<<8;}
#define GPIOC_3_IN_FLOAT()  {GPIOC->CRL&=0XFFFF0FFF;GPIOC->CRL|=4<<12;}
#define GPIOC_4_IN_FLOAT()  {GPIOC->CRL&=0XFFF0FFFF;GPIOC->CRL|=4<<16;}
#define GPIOC_5_IN_FLOAT()  {GPIOC->CRL&=0XFF0FFFFF;GPIOC->CRL|=4<<20;}
#define GPIOC_6_IN_FLOAT()  {GPIOC->CRL&=0XF0FFFFFF;GPIOC->CRL|=4<<24;}
#define GPIOC_7_IN_FLOAT()  {GPIOC->CRL&=0X0FFFFFFF;GPIOC->CRL|=4<<28;}
#define GPIOC_8_IN_FLOAT()  {GPIOC->CRH&=0XFFFFFFF0;GPIOC->CRH|=4<<0;}
#define GPIOC_9_IN_FLOAT()  {GPIOC->CRH&=0XFFFFFF0F;GPIOC->CRH|=4<<4;}
#define GPIOC_10_IN_FLOAT() {GPIOC->CRH&=0XFFFFF0FF;GPIOC->CRH|=4<<8;}
#define GPIOC_11_IN_FLOAT() {GPIOC->CRH&=0XFFFF0FFF;GPIOC->CRH|=4<<12;}
#define GPIOC_12_IN_FLOAT() {GPIOC->CRH&=0XFFF0FFFF;GPIOC->CRH|=4<<16;}
#define GPIOC_13_IN_FLOAT() {GPIOC->CRH&=0XFF0FFFFF;GPIOC->CRH|=4<<20;}
#define GPIOC_14_IN_FLOAT() {GPIOC->CRH&=0XF0FFFFFF;GPIOC->CRH|=4<<24;}
#define GPIOC_15_IN_FLOAT() {GPIOC->CRH&=0X0FFFFFFF;GPIOC->CRH|=4<<28;}


#define GPIOD_0_IN_FLOAT()  {GPIOD->CRL&=0XFFFFFFF0;GPIOD->CRL|=4<<0;}
#define GPIOD_1_IN_FLOAT()  {GPIOD->CRL&=0XFFFFFF0F;GPIOD->CRL|=4<<4;}
#define GPIOD_2_IN_FLOAT()  {GPIOD->CRL&=0XFFFFF0FF;GPIOD->CRL|=4<<8;}
#define GPIOD_3_IN_FLOAT()  {GPIOD->CRL&=0XFFFF0FFF;GPIOD->CRL|=4<<12;}
#define GPIOD_4_IN_FLOAT()  {GPIOD->CRL&=0XFFF0FFFF;GPIOD->CRL|=4<<16;}
#define GPIOD_5_IN_FLOAT()  {GPIOD->CRL&=0XFF0FFFFF;GPIOD->CRL|=4<<20;}
#define GPIOD_6_IN_FLOAT()  {GPIOD->CRL&=0XF0FFFFFF;GPIOD->CRL|=4<<24;}
#define GPIOD_7_IN_FLOAT()  {GPIOD->CRL&=0X0FFFFFFF;GPIOD->CRL|=4<<28;}
#define GPIOD_8_IN_FLOAT()  {GPIOD->CRH&=0XFFFFFFF0;GPIOD->CRH|=4<<0;}
#define GPIOD_9_IN_FLOAT()  {GPIOD->CRH&=0XFFFFFF0F;GPIOD->CRH|=4<<4;}
#define GPIOD_10_IN_FLOAT() {GPIOD->CRH&=0XFFFFF0FF;GPIOD->CRH|=4<<8;}
#define GPIOD_11_IN_FLOAT() {GPIOD->CRH&=0XFFFF0FFF;GPIOD->CRH|=4<<12;}
#define GPIOD_12_IN_FLOAT() {GPIOD->CRH&=0XFFF0FFFF;GPIOD->CRH|=4<<16;}
#define GPIOD_13_IN_FLOAT() {GPIOD->CRH&=0XFF0FFFFF;GPIOD->CRH|=4<<20;}
#define GPIOD_14_IN_FLOAT() {GPIOD->CRH&=0XF0FFFFFF;GPIOD->CRH|=4<<24;}
#define GPIOD_15_IN_FLOAT() {GPIOD->CRH&=0X0FFFFFFF;GPIOD->CRH|=4<<28;}


#define GPIOE_0_IN_FLOAT()  {GPIOE->CRL&=0XFFFFFFF0;GPIOE->CRL|=4<<0;}
#define GPIOE_1_IN_FLOAT()  {GPIOE->CRL&=0XFFFFFF0F;GPIOE->CRL|=4<<4;}
#define GPIOE_2_IN_FLOAT()  {GPIOE->CRL&=0XFFFFF0FF;GPIOE->CRL|=4<<8;}
#define GPIOE_3_IN_FLOAT()  {GPIOE->CRL&=0XFFFF0FFF;GPIOE->CRL|=4<<12;}
#define GPIOE_4_IN_FLOAT()  {GPIOE->CRL&=0XFFF0FFFF;GPIOE->CRL|=4<<16;}
#define GPIOE_5_IN_FLOAT()  {GPIOE->CRL&=0XFF0FFFFF;GPIOE->CRL|=4<<20;}
#define GPIOE_6_IN_FLOAT()  {GPIOE->CRL&=0XF0FFFFFF;GPIOE->CRL|=4<<24;}
#define GPIOE_7_IN_FLOAT()  {GPIOE->CRL&=0X0FFFFFFF;GPIOE->CRL|=4<<28;}
#define GPIOE_8_IN_FLOAT()  {GPIOE->CRH&=0XFFFFFFF0;GPIOE->CRH|=4<<0;}
#define GPIOE_9_IN_FLOAT()  {GPIOE->CRH&=0XFFFFFF0F;GPIOE->CRH|=4<<4;}
#define GPIOE_10_IN_FLOAT() {GPIOE->CRH&=0XFFFFF0FF;GPIOE->CRH|=4<<8;}
#define GPIOE_11_IN_FLOAT() {GPIOE->CRH&=0XFFFF0FFF;GPIOE->CRH|=4<<12;}
#define GPIOE_12_IN_FLOAT() {GPIOE->CRH&=0XFFF0FFFF;GPIOE->CRH|=4<<16;}
#define GPIOE_13_IN_FLOAT() {GPIOE->CRH&=0XFF0FFFFF;GPIOE->CRH|=4<<20;}
#define GPIOE_14_IN_FLOAT() {GPIOE->CRH&=0XF0FFFFFF;GPIOE->CRH|=4<<24;}
#define GPIOE_15_IN_FLOAT() {GPIOE->CRH&=0X0FFFFFFF;GPIOE->CRH|=4<<28;}


#define GPIOF_0_IN_FLOAT()  {GPIOF->CRL&=0XFFFFFFF0;GPIOF->CRL|=4<<0;}
#define GPIOF_1_IN_FLOAT()  {GPIOF->CRL&=0XFFFFFF0F;GPIOF->CRL|=4<<4;}
#define GPIOF_2_IN_FLOAT()  {GPIOF->CRL&=0XFFFFF0FF;GPIOF->CRL|=4<<8;}
#define GPIOF_3_IN_FLOAT()  {GPIOF->CRL&=0XFFFF0FFF;GPIOF->CRL|=4<<12;}
#define GPIOF_4_IN_FLOAT()  {GPIOF->CRL&=0XFFF0FFFF;GPIOF->CRL|=4<<16;}
#define GPIOF_5_IN_FLOAT()  {GPIOF->CRL&=0XFF0FFFFF;GPIOF->CRL|=4<<20;}
#define GPIOF_6_IN_FLOAT()  {GPIOF->CRL&=0XF0FFFFFF;GPIOF->CRL|=4<<24;}
#define GPIOF_7_IN_FLOAT()  {GPIOF->CRL&=0X0FFFFFFF;GPIOF->CRL|=4<<28;}
#define GPIOF_8_IN_FLOAT()  {GPIOF->CRH&=0XFFFFFFF0;GPIOF->CRH|=4<<0;}
#define GPIOF_9_IN_FLOAT()  {GPIOF->CRH&=0XFFFFFF0F;GPIOF->CRH|=4<<4;}
#define GPIOF_10_IN_FLOAT() {GPIOF->CRH&=0XFFFFF0FF;GPIOF->CRH|=4<<8;}
#define GPIOF_11_IN_FLOAT() {GPIOF->CRH&=0XFFFF0FFF;GPIOF->CRH|=4<<12;}
#define GPIOF_12_IN_FLOAT() {GPIOF->CRH&=0XFFF0FFFF;GPIOF->CRH|=4<<16;}
#define GPIOF_13_IN_FLOAT() {GPIOF->CRH&=0XFF0FFFFF;GPIOF->CRH|=4<<20;}
#define GPIOF_14_IN_FLOAT() {GPIOF->CRH&=0XF0FFFFFF;GPIOF->CRH|=4<<24;}
#define GPIOF_15_IN_FLOAT() {GPIOF->CRH&=0X0FFFFFFF;GPIOF->CRH|=4<<28;}


#define GPIOG_0_IN_FLOAT()  {GPIOG->CRL&=0XFFFFFFF0;GPIOG->CRL|=4<<0;}
#define GPIOG_1_IN_FLOAT()  {GPIOG->CRL&=0XFFFFFF0F;GPIOG->CRL|=4<<4;}
#define GPIOG_2_IN_FLOAT()  {GPIOG->CRL&=0XFFFFF0FF;GPIOG->CRL|=4<<8;}
#define GPIOG_3_IN_FLOAT()  {GPIOG->CRL&=0XFFFF0FFF;GPIOG->CRL|=4<<12;}
#define GPIOG_4_IN_FLOAT()  {GPIOG->CRL&=0XFFF0FFFF;GPIOG->CRL|=4<<16;}
#define GPIOG_5_IN_FLOAT()  {GPIOG->CRL&=0XFF0FFFFF;GPIOG->CRL|=4<<20;}
#define GPIOG_6_IN_FLOAT()  {GPIOG->CRL&=0XF0FFFFFF;GPIOG->CRL|=4<<24;}
#define GPIOG_7_IN_FLOAT()  {GPIOG->CRL&=0X0FFFFFFF;GPIOG->CRL|=4<<28;}
#define GPIOG_8_IN_FLOAT()  {GPIOG->CRH&=0XFFFFFFF0;GPIOG->CRH|=4<<0;}
#define GPIOG_9_IN_FLOAT()  {GPIOG->CRH&=0XFFFFFF0F;GPIOG->CRH|=4<<4;}
#define GPIOG_10_IN_FLOAT() {GPIOG->CRH&=0XFFFFF0FF;GPIOG->CRH|=4<<8;}
#define GPIOG_11_IN_FLOAT() {GPIOG->CRH&=0XFFFF0FFF;GPIOG->CRH|=4<<12;}
#define GPIOG_12_IN_FLOAT() {GPIOG->CRH&=0XFFF0FFFF;GPIOG->CRH|=4<<16;}
#define GPIOG_13_IN_FLOAT() {GPIOG->CRH&=0XFF0FFFFF;GPIOG->CRH|=4<<20;}
#define GPIOG_14_IN_FLOAT() {GPIOG->CRH&=0XF0FFFFFF;GPIOG->CRH|=4<<24;}
#define GPIOG_15_IN_FLOAT() {GPIOG->CRH&=0X0FFFFFFF;GPIOG->CRH|=4<<28;}



#define GPIOA_0_IN_ANALOG()  {GPIOA->CRL&=0XFFFFFFF0;}
#define GPIOA_1_IN_ANALOG()  {GPIOA->CRL&=0XFFFFFF0F;}
#define GPIOA_2_IN_ANALOG()  {GPIOA->CRL&=0XFFFFF0FF;}
#define GPIOA_3_IN_ANALOG()  {GPIOA->CRL&=0XFFFF0FFF;}
#define GPIOA_4_IN_ANALOG()  {GPIOA->CRL&=0XFFF0FFFF;}
#define GPIOA_5_IN_ANALOG()  {GPIOA->CRL&=0XFF0FFFFF;}
#define GPIOA_6_IN_ANALOG()  {GPIOA->CRL&=0XF0FFFFFF;}
#define GPIOA_7_IN_ANALOG()  {GPIOA->CRL&=0X0FFFFFFF;}
#define GPIOA_8_IN_ANALOG()  {GPIOA->CRH&=0XFFFFFFF0;}
#define GPIOA_9_IN_ANALOG()  {GPIOA->CRH&=0XFFFFFF0F;}
#define GPIOA_10_IN_ANALOG() {GPIOA->CRH&=0XFFFFF0FF;}
#define GPIOA_11_IN_ANALOG() {GPIOA->CRH&=0XFFFF0FFF;}
#define GPIOA_12_IN_ANALOG() {GPIOA->CRH&=0XFFF0FFFF;}
#define GPIOA_13_IN_ANALOG() {GPIOA->CRH&=0XFF0FFFFF;}
#define GPIOA_14_IN_ANALOG() {GPIOA->CRH&=0XF0FFFFFF;}
#define GPIOA_15_IN_ANALOG() {GPIOA->CRH&=0X0FFFFFFF;}

#define GPIOB_0_IN_ANALOG()  {GPIOB->CRL&=0XFFFFFFF0;}
#define GPIOB_1_IN_ANALOG()  {GPIOB->CRL&=0XFFFFFF0F;}
#define GPIOB_2_IN_ANALOG()  {GPIOB->CRL&=0XFFFFF0FF;}
#define GPIOB_3_IN_ANALOG()  {GPIOB->CRL&=0XFFFF0FFF;}
#define GPIOB_4_IN_ANALOG()  {GPIOB->CRL&=0XFFF0FFFF;}
#define GPIOB_5_IN_ANALOG()  {GPIOB->CRL&=0XFF0FFFFF;}
#define GPIOB_6_IN_ANALOG()  {GPIOB->CRL&=0XF0FFFFFF;}
#define GPIOB_7_IN_ANALOG()  {GPIOB->CRL&=0X0FFFFFFF;}
#define GPIOB_8_IN_ANALOG()  {GPIOB->CRH&=0XFFFFFFF0;}
#define GPIOB_9_IN_ANALOG()  {GPIOB->CRH&=0XFFFFFF0F;}
#define GPIOB_10_IN_ANALOG() {GPIOB->CRH&=0XFFFFF0FF;}
#define GPIOB_11_IN_ANALOG() {GPIOB->CRH&=0XFFFF0FFF;}
#define GPIOB_12_IN_ANALOG() {GPIOB->CRH&=0XFFF0FFFF;}
#define GPIOB_13_IN_ANALOG() {GPIOB->CRH&=0XFF0FFFFF;}
#define GPIOB_14_IN_ANALOG() {GPIOB->CRH&=0XF0FFFFFF;}
#define GPIOB_15_IN_ANALOG() {GPIOB->CRH&=0X0FFFFFFF;}


#define GPIOC_0_IN_ANALOG()  {GPIOC->CRL&=0XFFFFFFF0;}
#define GPIOC_1_IN_ANALOG()  {GPIOC->CRL&=0XFFFFFF0F;}
#define GPIOC_2_IN_ANALOG()  {GPIOC->CRL&=0XFFFFF0FF;}
#define GPIOC_3_IN_ANALOG()  {GPIOC->CRL&=0XFFFF0FFF;}
#define GPIOC_4_IN_ANALOG()  {GPIOC->CRL&=0XFFF0FFFF;}
#define GPIOC_5_IN_ANALOG()  {GPIOC->CRL&=0XFF0FFFFF;}
#define GPIOC_6_IN_ANALOG()  {GPIOC->CRL&=0XF0FFFFFF;}
#define GPIOC_7_IN_ANALOG()  {GPIOC->CRL&=0X0FFFFFFF;}
#define GPIOC_8_IN_ANALOG()  {GPIOC->CRH&=0XFFFFFFF0;}
#define GPIOC_9_IN_ANALOG()  {GPIOC->CRH&=0XFFFFFF0F;}
#define GPIOC_10_IN_ANALOG() {GPIOC->CRH&=0XFFFFF0FF;}
#define GPIOC_11_IN_ANALOG() {GPIOC->CRH&=0XFFFF0FFF;}
#define GPIOC_12_IN_ANALOG() {GPIOC->CRH&=0XFFF0FFFF;}
#define GPIOC_13_IN_ANALOG() {GPIOC->CRH&=0XFF0FFFFF;}
#define GPIOC_14_IN_ANALOG() {GPIOC->CRH&=0XF0FFFFFF;}
#define GPIOC_15_IN_ANALOG() {GPIOC->CRH&=0X0FFFFFFF;}


#define GPIOD_0_IN_ANALOG()  {GPIOD->CRL&=0XFFFFFFF0;}
#define GPIOD_1_IN_ANALOG()  {GPIOD->CRL&=0XFFFFFF0F;}
#define GPIOD_2_IN_ANALOG()  {GPIOD->CRL&=0XFFFFF0FF;}
#define GPIOD_3_IN_ANALOG()  {GPIOD->CRL&=0XFFFF0FFF;}
#define GPIOD_4_IN_ANALOG()  {GPIOD->CRL&=0XFFF0FFFF;}
#define GPIOD_5_IN_ANALOG()  {GPIOD->CRL&=0XFF0FFFFF;}
#define GPIOD_6_IN_ANALOG()  {GPIOD->CRL&=0XF0FFFFFF;}
#define GPIOD_7_IN_ANALOG()  {GPIOD->CRL&=0X0FFFFFFF;}
#define GPIOD_8_IN_ANALOG()  {GPIOD->CRH&=0XFFFFFFF0;}
#define GPIOD_9_IN_ANALOG()  {GPIOD->CRH&=0XFFFFFF0F;}
#define GPIOD_10_IN_ANALOG() {GPIOD->CRH&=0XFFFFF0FF;}
#define GPIOD_11_IN_ANALOG() {GPIOD->CRH&=0XFFFF0FFF;}
#define GPIOD_12_IN_ANALOG() {GPIOD->CRH&=0XFFF0FFFF;}
#define GPIOD_13_IN_ANALOG() {GPIOD->CRH&=0XFF0FFFFF;}
#define GPIOD_14_IN_ANALOG() {GPIOD->CRH&=0XF0FFFFFF;}
#define GPIOD_15_IN_ANALOG() {GPIOD->CRH&=0X0FFFFFFF;}


#define GPIOE_0_IN_ANALOG()  {GPIOE->CRL&=0XFFFFFFF0;}
#define GPIOE_1_IN_ANALOG()  {GPIOE->CRL&=0XFFFFFF0F;}
#define GPIOE_2_IN_ANALOG()  {GPIOE->CRL&=0XFFFFF0FF;}
#define GPIOE_3_IN_ANALOG()  {GPIOE->CRL&=0XFFFF0FFF;}
#define GPIOE_4_IN_ANALOG()  {GPIOE->CRL&=0XFFF0FFFF;}
#define GPIOE_5_IN_ANALOG()  {GPIOE->CRL&=0XFF0FFFFF;}
#define GPIOE_6_IN_ANALOG()  {GPIOE->CRL&=0XF0FFFFFF;}
#define GPIOE_7_IN_ANALOG()  {GPIOE->CRL&=0X0FFFFFFF;}
#define GPIOE_8_IN_ANALOG()  {GPIOE->CRH&=0XFFFFFFF0;}
#define GPIOE_9_IN_ANALOG()  {GPIOE->CRH&=0XFFFFFF0F;}
#define GPIOE_10_IN_ANALOG() {GPIOE->CRH&=0XFFFFF0FF;}
#define GPIOE_11_IN_ANALOG() {GPIOE->CRH&=0XFFFF0FFF;}
#define GPIOE_12_IN_ANALOG() {GPIOE->CRH&=0XFFF0FFFF;}
#define GPIOE_13_IN_ANALOG() {GPIOE->CRH&=0XFF0FFFFF;}
#define GPIOE_14_IN_ANALOG() {GPIOE->CRH&=0XF0FFFFFF;}
#define GPIOE_15_IN_ANALOG() {GPIOE->CRH&=0X0FFFFFFF;}


#define GPIOF_0_IN_ANALOG()  {GPIOF->CRL&=0XFFFFFFF0;}
#define GPIOF_1_IN_ANALOG()  {GPIOF->CRL&=0XFFFFFF0F;}
#define GPIOF_2_IN_ANALOG()  {GPIOF->CRL&=0XFFFFF0FF;}
#define GPIOF_3_IN_ANALOG()  {GPIOF->CRL&=0XFFFF0FFF;}
#define GPIOF_4_IN_ANALOG()  {GPIOF->CRL&=0XFFF0FFFF;}
#define GPIOF_5_IN_ANALOG()  {GPIOF->CRL&=0XFF0FFFFF;}
#define GPIOF_6_IN_ANALOG()  {GPIOF->CRL&=0XF0FFFFFF;}
#define GPIOF_7_IN_ANALOG()  {GPIOF->CRL&=0X0FFFFFFF;}
#define GPIOF_8_IN_ANALOG()  {GPIOF->CRH&=0XFFFFFFF0;}
#define GPIOF_9_IN_ANALOG()  {GPIOF->CRH&=0XFFFFFF0F;}
#define GPIOF_10_IN_ANALOG() {GPIOF->CRH&=0XFFFFF0FF;}
#define GPIOF_11_IN_ANALOG() {GPIOF->CRH&=0XFFFF0FFF;}
#define GPIOF_12_IN_ANALOG() {GPIOF->CRH&=0XFFF0FFFF;}
#define GPIOF_13_IN_ANALOG() {GPIOF->CRH&=0XFF0FFFFF;}
#define GPIOF_14_IN_ANALOG() {GPIOF->CRH&=0XF0FFFFFF;}
#define GPIOF_15_IN_ANALOG() {GPIOF->CRH&=0X0FFFFFFF;}


#define GPIOG_0_IN_ANALOG()  {GPIOG->CRL&=0XFFFFFFF0;}
#define GPIOG_1_IN_ANALOG()  {GPIOG->CRL&=0XFFFFFF0F;}
#define GPIOG_2_IN_ANALOG()  {GPIOG->CRL&=0XFFFFF0FF;}
#define GPIOG_3_IN_ANALOG()  {GPIOG->CRL&=0XFFFF0FFF;}
#define GPIOG_4_IN_ANALOG()  {GPIOG->CRL&=0XFFF0FFFF;}
#define GPIOG_5_IN_ANALOG()  {GPIOG->CRL&=0XFF0FFFFF;}
#define GPIOG_6_IN_ANALOG()  {GPIOG->CRL&=0XF0FFFFFF;}
#define GPIOG_7_IN_ANALOG()  {GPIOG->CRL&=0X0FFFFFFF;}
#define GPIOG_8_IN_ANALOG()  {GPIOG->CRH&=0XFFFFFFF0;}
#define GPIOG_9_IN_ANALOG()  {GPIOG->CRH&=0XFFFFFF0F;}
#define GPIOG_10_IN_ANALOG() {GPIOG->CRH&=0XFFFFF0FF;}
#define GPIOG_11_IN_ANALOG() {GPIOG->CRH&=0XFFFF0FFF;}
#define GPIOG_12_IN_ANALOG() {GPIOG->CRH&=0XFFF0FFFF;}
#define GPIOG_13_IN_ANALOG() {GPIOG->CRH&=0XFF0FFFFF;}
#define GPIOG_14_IN_ANALOG() {GPIOG->CRH&=0XF0FFFFFF;}
#define GPIOG_15_IN_ANALOG() {GPIOG->CRH&=0X0FFFFFFF;}


#define _Mode_IN_ANALOG    0x0
#define _Mode_IN_FLOAT     0x04
#define _Mode_IN_UD        0x08
#define _Mode_IN_DOWN      0x08
#define _Mode_Out_PP       0x03
#define _Mode_Out_OD       0x07#define _Mode_OUT_AFPP     0x0B
#define _Mode_OUT_AFOD     0x0F


#define _PORTA_  2
#define _PORTB_  3
#define _PORTC_  4
#define _PORTD_  5
#define _PORTE_  6
#define _PORTF_  7
#define _PORTG_  8


void JTAG_MODE_SET(u8 mode);
void GPIO_Config(u8 Pin_Group,u8 Pin_Num,u8 Pin_Mode );

#endif
